const std = @import("std");
const c = @cImport({
    @cInclude("defun_impl.h");
});

const CmdFunc = struct {
    func: *const fn (args: c.CmdArgs) callconv(.c) void,
    desc: []const u8,
};

const funcMap: std.StaticStringMap(CmdFunc) = .initComptime(&.{
    .{ "NOTHING", CmdFunc{ .func = c.nulcmd, .desc = "Do nothing" } },
    .{ "ESCMAP", CmdFunc{ .func = c.escmap, .desc = "ESC map" } },
    .{ "ESCBMAP", CmdFunc{ .func = c.escbmap, .desc = "ESC [ map" } },
    .{ "MULTIMAP", CmdFunc{ .func = c.multimap, .desc = "multimap" } },
    .{ "NEXT_PAGE", CmdFunc{ .func = c.pgFore, .desc = "Scroll down one page" } },
    .{ "PREV_PAGE", CmdFunc{ .func = c.pgBack, .desc = "Scroll up one page" } },
    .{ "NEXT_HALF_PAGE", CmdFunc{ .func = c.hpgFore, .desc = "Scroll down half a page" } },
    .{ "PREV_HALF_PAGE", CmdFunc{ .func = c.hpgBack, .desc = "Scroll up half a page" } },
    .{ "UP", CmdFunc{ .func = c.lup1, .desc = "Scroll the screen up one line" } },
    .{ "DOWN", CmdFunc{ .func = c.ldown1, .desc = "Scroll the screen down one line" } },
    .{ "CENTER_V", CmdFunc{ .func = c.ctrCsrV, .desc = "Center on cursor line" } },
    .{ "CENTER_H", CmdFunc{ .func = c.ctrCsrH, .desc = "Center on cursor column" } },
    .{ "REDRAW", CmdFunc{ .func = c.rdrwSc, .desc = "Draw the screen anew" } },
    .{ "SEARCH", CmdFunc{ .func = c.srchfor, .desc = "Search forward" } },
    .{ "ISEARCH", CmdFunc{ .func = c.isrchfor, .desc = "Incremental search forward" } },
    .{ "SEARCH_BACK", CmdFunc{ .func = c.srchbak, .desc = "Search backward" } },
    .{ "ISEARCH_BACK", CmdFunc{ .func = c.isrchbak, .desc = "Incremental search backward" } },
    .{ "SEARCH_NEXT", CmdFunc{ .func = c.srchnxt, .desc = "Continue search forward" } },
    .{ "SEARCH_PREV", CmdFunc{ .func = c.srchprv, .desc = "Continue search backward" } },
    .{ "SHIFT_LEFT", CmdFunc{ .func = c.shiftl, .desc = "Shift screen left" } },
    .{ "SHIFT_RIGHT", CmdFunc{ .func = c.shiftr, .desc = "Shift screen right" } },
    .{ "RIGHT", CmdFunc{ .func = c.col1R, .desc = "Shift screen one column right" } },
    .{ "LEFT", CmdFunc{ .func = c.col1L, .desc = "Shift screen one column left" } },
    .{ "SETENV", CmdFunc{ .func = c.setEnv, .desc = "Set environment variable" } },
    .{ "PIPE_BUF", CmdFunc{ .func = c.pipeBuf, .desc = "Pipe current buffer through a shell command and display output" } },
    .{ "PIPE_SHELL", CmdFunc{ .func = c.pipesh, .desc = "Execute shell command and display output" } },
    .{ "READ_SHELL", CmdFunc{ .func = c.readsh, .desc = "Execute shell command and display output" } },
    .{ "SHELL", CmdFunc{ .func = c.execsh, .desc = "Execute shell command and display output" } },
    .{ "LOAD", CmdFunc{ .func = c.ldfile, .desc = "Open local file in a new buffer" } },
    .{ "HELP", CmdFunc{ .func = c.ldhelp, .desc = "Show help panel" } },
    .{ "MOVE_LEFT", CmdFunc{ .func = c.movL, .desc = "Cursor left" } },
    .{ "MOVE_LEFT1", CmdFunc{ .func = c.movL1, .desc = "Cursor left. With edge touched, slide" } },
    .{ "MOVE_DOWN", CmdFunc{ .func = c.movD, .desc = "Cursor down" } },
    .{ "MOVE_DOWN1", CmdFunc{ .func = c.movD1, .desc = "Cursor down. With edge touched, slide" } },
    .{ "MOVE_UP", CmdFunc{ .func = c.movU, .desc = "Cursor up" } },
    .{ "MOVE_UP1", CmdFunc{ .func = c.movU1, .desc = "Cursor up. With edge touched, slide" } },
    .{ "MOVE_RIGHT", CmdFunc{ .func = c.movR, .desc = "Cursor right" } },
    .{ "MOVE_RIGHT1", CmdFunc{ .func = c.movR1, .desc = "Cursor right. With edge touched, slide" } },
    .{ "PREV_WORD", CmdFunc{ .func = c.movLW, .desc = "Move to the previous word" } },
    .{ "NEXT_WORD", CmdFunc{ .func = c.movRW, .desc = "Move to the next word" } },
    .{ "ABORT", CmdFunc{ .func = c.quitfm, .desc = "Quit without confirmation" } },
    .{ "QUIT", CmdFunc{ .func = c.qquitfm, .desc = "Quit with confirmation request" } },
    .{ "SELECT", CmdFunc{ .func = c.selBuf, .desc = "Display buffer-stack panel" } },
    .{ "SUSPEND", CmdFunc{ .func = c.susp, .desc = "Suspend w3m to background" } },
    .{ "GOTO_LINE", CmdFunc{ .func = c.goLine, .desc = "Go to the specified line" } },
    .{ "BEGIN", CmdFunc{ .func = c.goLineF, .desc = "Go to the first line" } },
    .{ "END", CmdFunc{ .func = c.goLineL, .desc = "Go to the last line" } },
    .{ "LINE_BEGIN", CmdFunc{ .func = c.linbeg, .desc = "Go to the beginning of the line" } },
    .{ "LINE_END", CmdFunc{ .func = c.linend, .desc = "Go to the end of the line" } },
    .{ "EDIT", CmdFunc{ .func = c.editBf, .desc = "Edit local source" } },
    .{ "EDIT_SCREEN", CmdFunc{ .func = c.editScr, .desc = "Edit rendered copy of document" } },
    .{ "MARK", CmdFunc{ .func = c._mark, .desc = "Set/unset mark" } },
    .{ "NEXT_MARK", CmdFunc{ .func = c.nextMk, .desc = "Go to the next mark" } },
    .{ "PREV_MARK", CmdFunc{ .func = c.prevMk, .desc = "Go to the previous mark" } },
    .{ "REG_MARK", CmdFunc{ .func = c.reMark, .desc = "Mark all occurences of a pattern" } },
    .{ "GOTO_LINK", CmdFunc{ .func = c.followA, .desc = "Follow current hyperlink in a new buffer" } },
    .{ "VIEW_IMAGE", CmdFunc{ .func = c.followI, .desc = "Display image in viewer" } },
    .{ "SUBMIT", CmdFunc{ .func = c.submitForm, .desc = "Submit form" } },
    .{ "LINK_BEGIN", CmdFunc{ .func = c.topA, .desc = "Move to the first hyperlink" } },
    .{ "LINK_END", CmdFunc{ .func = c.lastA, .desc = "Move to the last hyperlink" } },
    .{ "LINK_N", CmdFunc{ .func = c.nthA, .desc = "Go to the nth link" } },
    .{ "NEXT_LINK", CmdFunc{ .func = c.nextA, .desc = "Move to the next hyperlink" } },
    .{ "PREV_LINK", CmdFunc{ .func = c.prevA, .desc = "Move to the previous hyperlink" } },
    .{ "NEXT_VISITED", CmdFunc{ .func = c.nextVA, .desc = "Move to the next visited hyperlink" } },
    .{ "PREV_VISITED", CmdFunc{ .func = c.prevVA, .desc = "Move to the previous visited hyperlink" } },
    .{ "NEXT_LEFT", CmdFunc{ .func = c.nextL, .desc = "Move left to the next hyperlink" } },
    .{ "NEXT_LEFT_UP", CmdFunc{ .func = c.nextLU, .desc = "Move left or upward to the next hyperlink" } },
    .{ "NEXT_RIGHT", CmdFunc{ .func = c.nextR, .desc = "Move right to the next hyperlink" } },
    .{ "NEXT_RIGHT_DOWN", CmdFunc{ .func = c.nextRD, .desc = "Move right or downward to the next hyperlink" } },
    .{ "NEXT_DOWN", CmdFunc{ .func = c.nextD, .desc = "Move downward to the next hyperlink" } },
    .{ "NEXT_UP", CmdFunc{ .func = c.nextU, .desc = "Move upward to the next hyperlink" } },
    .{ "NEXT", CmdFunc{ .func = c.nextBf, .desc = "Switch to the next buffer" } },
    .{ "PREV", CmdFunc{ .func = c.prevBf, .desc = "Switch to the previous buffer" } },
    .{ "BACK", CmdFunc{ .func = c.backBf, .desc = "Close current buffer and return to the one below in stack" } },
    .{ "DELETE_PREVBUF", CmdFunc{ .func = c.deletePrevBuf, .desc = "Delete previous buffer (mainly for local CGI-scripts)" } },
    .{ "GOTO", CmdFunc{ .func = c.goURL, .desc = "Open specified document in a new buffer" } },
    .{ "GOTO_HOME", CmdFunc{ .func = c.goHome, .desc = "Open home page in a new buffer" } },
    .{ "GOTO_RELATIVE", CmdFunc{ .func = c.gorURL, .desc = "Go to relative address" } },
    .{ "BOOKMARK", CmdFunc{ .func = c.ldBmark, .desc = "View bookmarks" } },
    .{ "ADD_BOOKMARK", CmdFunc{ .func = c.adBmark, .desc = "Add current page to bookmarks" } },
    .{ "OPTIONS", CmdFunc{ .func = c.ldOpt, .desc = "Display options setting panel" } },
    .{ "SET_OPTION", CmdFunc{ .func = c.setOpt, .desc = "Set option" } },
    .{ "MSGS", CmdFunc{ .func = c.msgs, .desc = "Display error messages" } },
    .{ "INFO", CmdFunc{ .func = c.pginfo, .desc = "Display information about the current document" } },
    .{ "LINK_MENU", CmdFunc{ .func = c.linkMn, .desc = "Pop up link element menu" } },
    .{ "ACCESSKEY", CmdFunc{ .func = c.accessKey, .desc = "Pop up accesskey menu" } },
    .{ "LIST_MENU", CmdFunc{ .func = c.listMn, .desc = "Pop up menu for hyperlinks to browse to" } },
    .{ "MOVE_LIST_MENU", CmdFunc{ .func = c.movlistMn, .desc = "Pop up menu to navigate between hyperlinks" } },
    .{ "LIST", CmdFunc{ .func = c.linkLst, .desc = "Show all URLs referenced" } },
    .{ "COOKIE", CmdFunc{ .func = c.cooLst, .desc = "View cookie list" } },
    .{ "HISTORY", CmdFunc{ .func = c.ldHist, .desc = "Show browsing history" } },
    .{ "SAVE_LINK", CmdFunc{ .func = c.svA, .desc = "Save hyperlink target" } },
    .{ "SAVE_IMAGE", CmdFunc{ .func = c.svI, .desc = "Save inline image" } },
    .{ "PRINT", CmdFunc{ .func = c.svBuf, .desc = "Save rendered document" } },
    .{ "SAVE", CmdFunc{ .func = c.svSrc, .desc = "Save document source" } },
    .{ "PEEK_LINK", CmdFunc{ .func = c.peekURL, .desc = "Show target address" } },
    .{ "PEEK_IMG", CmdFunc{ .func = c.peekIMG, .desc = "Show image address" } },
    .{ "PEEK", CmdFunc{ .func = c.curURL, .desc = "Show current address" } },
    .{ "SOURCE", CmdFunc{ .func = c.vwSrc, .desc = "Toggle between HTML shown or processed" } },
    .{ "RELOAD", CmdFunc{ .func = c.reload, .desc = "Load current document anew" } },
    .{ "RESHAPE", CmdFunc{ .func = c.reshape, .desc = "Re-render document" } },
    .{ "CHARSET", CmdFunc{ .func = c.docCSet, .desc = "Change the character encoding for the current document" } },
    .{ "DEFAULT_CHARSET", CmdFunc{ .func = c.defCSet, .desc = "Change the default character encoding" } },
    .{ "MARK_URL", CmdFunc{ .func = c.chkURL, .desc = "Turn URL-like strings into hyperlinks" } },
    .{ "MARK_WORD", CmdFunc{ .func = c.chkWORD, .desc = "Turn current word into hyperlink" } },
    .{ "MARK_MID", CmdFunc{ .func = c.chkNMID, .desc = "Turn Message-ID-like strings into hyperlinks" } },
    .{ "FRAME", CmdFunc{ .func = c.rFrame, .desc = "Toggle rendering HTML frames" } },
    .{ "EXTERN", CmdFunc{ .func = c.extbrz, .desc = "Display using an external browser" } },
    .{ "EXTERN_LINK", CmdFunc{ .func = c.linkbrz, .desc = "Display target using an external browser" } },
    .{ "LINE_INFO", CmdFunc{ .func = c.curlno, .desc = "Display current position in document" } },
    .{ "DISPLAY_IMAGE", CmdFunc{ .func = c.dispI, .desc = "Restart loading and drawing of images" } },
    .{ "STOP_IMAGE", CmdFunc{ .func = c.stopI, .desc = "Stop loading and drawing of images" } },
    .{ "MOUSE_TOGGLE", CmdFunc{ .func = c.nulcmd, .desc = "Toggle mouse support" } },
    .{ "MOUSE", CmdFunc{ .func = c.nulcmd, .desc = "mouse operation" } },
    .{ "SGRMOUSE", CmdFunc{ .func = c.nulcmd, .desc = "SGR 1006 mouse operation" } },
    .{ "MOVE_MOUSE", CmdFunc{ .func = c.nulcmd, .desc = "Move cursor to mouse pointer" } },
    .{ "MENU_MOUSE", CmdFunc{ .func = c.nulcmd, .desc = "Pop up menu at mouse pointer" } },
    .{ "TAB_MOUSE", CmdFunc{ .func = c.nulcmd, .desc = "Select tab by mouse action" } },
    .{ "CLOSE_TAB_MOUSE", CmdFunc{ .func = c.nulcmd, .desc = "Close tab at mouse pointer" } },
    .{ "VERSION", CmdFunc{ .func = c.dispVer, .desc = "Display the version of w3m" } },
    .{ "WRAP_TOGGLE", CmdFunc{ .func = c.wrapToggle, .desc = "Toggle wrapping mode in searches" } },
    .{ "DICT_WORD", CmdFunc{ .func = c.dictword, .desc = "Execute dictionary command (see README.dict)" } },
    .{ "DICT_WORD_AT", CmdFunc{ .func = c.dictwordat, .desc = "Execute dictionary command for word at cursor" } },
    .{ "COMMAND", CmdFunc{ .func = c.execCmd, .desc = "Invoke w3m function(s)" } },
    .{ "ALARM", CmdFunc{ .func = c.setAlarm, .desc = "Set alarm" } },
    .{ "REINIT", CmdFunc{ .func = c.reinit, .desc = "Reload configuration file" } },
    .{ "DEFINE_KEY", CmdFunc{ .func = c.defKey, .desc = "Define a binding between a key stroke combination and a command" } },
    .{ "NEW_TAB", CmdFunc{ .func = c.newT, .desc = "Open a new tab (with current document)" } },
    .{ "CLOSE_TAB", CmdFunc{ .func = c.closeT, .desc = "Close tab" } },
    .{ "NEXT_TAB", CmdFunc{ .func = c.nextT, .desc = "Switch to the next tab" } },
    .{ "PREV_TAB", CmdFunc{ .func = c.prevT, .desc = "Switch to the previous tab" } },
    .{ "TAB_LINK", CmdFunc{ .func = c.tabA, .desc = "Follow current hyperlink in a new tab" } },
    .{ "TAB_GOTO", CmdFunc{ .func = c.tabURL, .desc = "Open specified document in a new tab" } },
    .{ "TAB_GOTO_RELATIVE", CmdFunc{ .func = c.tabrURL, .desc = "Open relative address in a new tab" } },
    .{ "TAB_RIGHT", CmdFunc{ .func = c.tabR, .desc = "Move right along the tab bar" } },
    .{ "TAB_LEFT", CmdFunc{ .func = c.tabL, .desc = "Move left along the tab bar" } },
    .{ "DOWNLOAD_LIST", CmdFunc{ .func = c.ldDL, .desc = "Display downloads panel" } },
    .{ "UNDO", CmdFunc{ .func = c.undoPos, .desc = "Cancel the last cursor movement" } },
    .{ "REDO", CmdFunc{ .func = c.redoPos, .desc = "Cancel the last undo" } },
    .{ "CURSOR_TOP", CmdFunc{ .func = c.cursorTop, .desc = "Move cursor to the top of the screen" } },
    .{ "CURSOR_MIDDLE", CmdFunc{ .func = c.cursorMiddle, .desc = "Move cursor to the middle of the screen" } },
    .{ "CURSOR_BOTTOM", CmdFunc{ .func = c.cursorBottom, .desc = "Move cursor to the bottom of the screen" } },
    .{ "MENU", CmdFunc{ .func = c.mainMn, .desc = "Pop up menu" } },
    .{ "SELECT_MENU", CmdFunc{ .func = c.selMn, .desc = "Pop up buffer-stack menu" } },
    .{ "TAB_MENU", CmdFunc{ .func = c.tabMn, .desc = "Pop up tab selection menu" } },
});
export fn w3mFunc(_cmd: [*c]const u8) void {
    if (_cmd) |cmd| {
        if (funcMap.get(std.mem.span(cmd))) |found| {
            found.func(.{});
        } else {
            std.log.warn("{s} not found", .{cmd});
        }
    } else {
        std.log.warn("null cmd", .{});
    }
}
