#define FUNCNAME_nulcmd 0
#define FUNCNAME_quitfm 3
#define FUNCNAME_accessKey 4
#define FUNCNAME_adBmark 5
#define FUNCNAME_setAlarm 6
#define FUNCNAME_backBf 7
#define FUNCNAME_goLineF 8
#define FUNCNAME_ldBmark 9
#define FUNCNAME_ctrCsrH 10
#define FUNCNAME_ctrCsrV 11
#define FUNCNAME_docCSet 12
#define FUNCNAME_closeT 13
#define FUNCNAME_execCmd 14
#define FUNCNAME_cooLst 15
#define FUNCNAME_cursorBottom 16
#define FUNCNAME_cursorMiddle 17
#define FUNCNAME_cursorTop 18
#define FUNCNAME_defCSet 19
#define FUNCNAME_defKey 20
#define FUNCNAME_deletePrevBuf 21
#define FUNCNAME_dictword 22
#define FUNCNAME_dictwordat 23
#define FUNCNAME_dispI 24
#define FUNCNAME_ldown1 25
#define FUNCNAME_svSrc 26
#define FUNCNAME_ldDL 27
#define FUNCNAME_editBf 28
#define FUNCNAME_editScr 29
#define FUNCNAME_goLineL 30
#define FUNCNAME_escbmap 31
#define FUNCNAME_escmap 32
#define FUNCNAME_execsh 33
#define FUNCNAME_extbrz 35
#define FUNCNAME_linkbrz 36
#define FUNCNAME_rFrame 37
#define FUNCNAME_goURL 38
#define FUNCNAME_goHome 39
#define FUNCNAME_goLine 40
#define FUNCNAME_followA 41
#define FUNCNAME_gorURL 42
#define FUNCNAME_ldhelp 43
#define FUNCNAME_ldHist 44
#define FUNCNAME_pginfo 45
#define FUNCNAME_susp 46
#define FUNCNAME_isrchfor 47
#define FUNCNAME_isrchbak 48
#define FUNCNAME_col1L 49
#define FUNCNAME_linbeg 50
#define FUNCNAME_linend 51
#define FUNCNAME_curlno 52
#define FUNCNAME_topA 53
#define FUNCNAME_lastA 54
#define FUNCNAME_linkMn 55
#define FUNCNAME_nthA 56
#define FUNCNAME_linkLst 57
#define FUNCNAME_listMn 58
#define FUNCNAME_ldfile 59
#define FUNCNAME_mainMn 60
#define FUNCNAME__mark 61
#define FUNCNAME_chkNMID 62
#define FUNCNAME_chkURL 63
#define FUNCNAME_chkWORD 64
#define FUNCNAME_movD 66
#define FUNCNAME_movD1 67
#define FUNCNAME_movL 68
#define FUNCNAME_movL1 69
#define FUNCNAME_movlistMn 70
#define FUNCNAME_movR 71
#define FUNCNAME_movR1 72
#define FUNCNAME_movU 73
#define FUNCNAME_movU1 74
#define FUNCNAME_msgs 75
#define FUNCNAME_multimap 76
#define FUNCNAME_newT 77
#define FUNCNAME_nextBf 78
#define FUNCNAME_nextD 79
#define FUNCNAME_hpgFore 80
#define FUNCNAME_nextL 81
#define FUNCNAME_nextLU 82
#define FUNCNAME_nextA 83
#define FUNCNAME_nextMk 84
#define FUNCNAME_pgFore 85
#define FUNCNAME_nextR 86
#define FUNCNAME_nextRD 87
#define FUNCNAME_nextT 88
#define FUNCNAME_nextU 89
#define FUNCNAME_nextVA 90
#define FUNCNAME_movRW 91
#define FUNCNAME_ldOpt 94
#define FUNCNAME_curURL 95
#define FUNCNAME_peekIMG 96
#define FUNCNAME_peekURL 97
#define FUNCNAME_pipeBuf 98
#define FUNCNAME_pipesh 99
#define FUNCNAME_prevBf 100
#define FUNCNAME_hpgBack 101
#define FUNCNAME_prevA 102
#define FUNCNAME_prevMk 103
#define FUNCNAME_pgBack 104
#define FUNCNAME_prevT 105
#define FUNCNAME_prevVA 106
#define FUNCNAME_movLW 107
#define FUNCNAME_svBuf 108
#define FUNCNAME_qquitfm 109
#define FUNCNAME_readsh 110
#define FUNCNAME_redoPos 111
#define FUNCNAME_rdrwSc 112
#define FUNCNAME_reMark 113
#define FUNCNAME_reinit 114
#define FUNCNAME_reload 115
#define FUNCNAME_reshape 116
#define FUNCNAME_col1R 117
#define FUNCNAME_svI 119
#define FUNCNAME_svA 120
#define FUNCNAME_srchfor 122
#define FUNCNAME_srchbak 123
#define FUNCNAME_srchnxt 125
#define FUNCNAME_srchprv 126
#define FUNCNAME_selBuf 127
#define FUNCNAME_selMn 128
#define FUNCNAME_setEnv 129
#define FUNCNAME_setOpt 130
#define FUNCNAME_shiftl 132
#define FUNCNAME_shiftr 133
#define FUNCNAME_vwSrc 134
#define FUNCNAME_stopI 135
#define FUNCNAME_submitForm 136
#define FUNCNAME_tabURL 138
#define FUNCNAME_tabrURL 139
#define FUNCNAME_tabL 140
#define FUNCNAME_tabA 141
#define FUNCNAME_tabMn 142
#define FUNCNAME_tabR 143
#define FUNCNAME_undoPos 144
#define FUNCNAME_lup1 145
#define FUNCNAME_dispVer 146
#define FUNCNAME_followI 149
#define FUNCNAME_wrapToggle 151
