#include "hash.h"
#include <stdio.h>
#include "funcname1.h"
static HashItem_si MyHashItem[] = {
    /* 0 */ {"SUSPEND", FUNCNAME_susp, &MyHashItem[1]},
    /* 1 */ {"SET_OPTION", FUNCNAME_setOpt, &MyHashItem[2]},
    /* 2 */ {"END", FUNCNAME_goLineL, NULL},
    /* 3 */ {"VIEW", FUNCNAME_vwSrc, NULL},
    /* 4 */ {"PREV_VISITED", FUNCNAME_prevVA, &MyHashItem[5]},
    /* 5 */ {"EXTERN", FUNCNAME_extbrz, NULL},
    /* 6 */ {"UNDO", FUNCNAME_undoPos, NULL},
    /* 7 */ {"SHELL", FUNCNAME_execsh, &MyHashItem[8]},
    /* 8 */ {"RIGHT", FUNCNAME_col1R, &MyHashItem[9]},
    /* 9 */ {"PREV_WORD", FUNCNAME_movLW, &MyHashItem[10]},
    /* 10 */ {"LEFT", FUNCNAME_col1L, &MyHashItem[11]},
    /* 11 */ {"INTERRUPT", FUNCNAME_susp, NULL},
    /* 12 */ {"TAB_GOTO_RELATIVE", FUNCNAME_tabrURL, NULL},
    /* 13 */ {"NEXT_UP", FUNCNAME_nextU, NULL},
    /* 14 */ {"CLOSE_TAB_MOUSE", FUNCNAME_closeTMs, NULL},
    /* 15 */ {"DOWN", FUNCNAME_ldown1, NULL},
    /* 16 */ {"HISTORY", FUNCNAME_ldHist, NULL},
    /* 17 */ {"SEARCH", FUNCNAME_srchfor, &MyHashItem[18]},
    /* 18 */ {"NEXT_VISITED", FUNCNAME_nextVA, &MyHashItem[19]},
    /* 19 */ {"NEXT_LEFT_UP", FUNCNAME_nextLU, &MyHashItem[20]},
    /* 20 */ {"MOVE_UP", FUNCNAME_movU, &MyHashItem[21]},
    /* 21 */ {"DOWNLOAD", FUNCNAME_svSrc, NULL},
    /* 22 */ {"VIEW_IMAGE", FUNCNAME_followI, &MyHashItem[23]},
    /* 23 */ {"MARK", FUNCNAME__mark, &MyHashItem[24]},
    /* 24 */ {"INFO", FUNCNAME_pginfo, NULL},
    /* 25 */ {"VERSION", FUNCNAME_dispVer, &MyHashItem[26]},
    /* 26 */ {"BEGIN", FUNCNAME_goLineF, NULL},
    /* 27 */ {"REDRAW", FUNCNAME_rdrwSc, NULL},
    /* 28 */ {"QUIT", FUNCNAME_qquitfm, &MyHashItem[29]},
    /* 29 */ {"DOWNLOAD_LIST", FUNCNAME_ldDL, NULL},
    /* 30 */ {"REG_MARK", FUNCNAME_reMark, NULL},
    /* 31 */ {"MOVE_RIGHT", FUNCNAME_movR, NULL},
    /* 32 */ {"MARK_MID", FUNCNAME_chkNMID, &MyHashItem[33]},
    /* 33 */ {"LOAD", FUNCNAME_ldfile, NULL},
    /* 34 */ {"EXEC_SHELL", FUNCNAME_execsh, NULL},
    /* 35 */ {"VIEW_BOOKMARK", FUNCNAME_ldBmark, &MyHashItem[36]},
    /* 36 */ {"TAB_MOUSE", FUNCNAME_tabMs, &MyHashItem[37]},
    /* 37 */ {"STOP_IMAGE", FUNCNAME_stopI, &MyHashItem[38]},
    /* 38 */ {"GOTO_HOME", FUNCNAME_goHome, NULL},
    /* 39 */ {"SHIFT_RIGHT", FUNCNAME_shiftr, &MyHashItem[40]},
    /* 40 */ {"SEARCH_NEXT", FUNCNAME_srchnxt, NULL},
    /* 41 */ {"PEEK", FUNCNAME_curURL, NULL},
    /* 42 */ {"DICT_WORD_AT", FUNCNAME_dictwordat, NULL},
    /* 43 */ {"SOURCE", FUNCNAME_vwSrc, &MyHashItem[44]},
    /* 44 */ {"SGRMOUSE", FUNCNAME_sgrmouse, &MyHashItem[45]},
    /* 45 */ {"SAVE_LINK", FUNCNAME_svA, &MyHashItem[46]},
    /* 46 */ {"GOTO", FUNCNAME_goURL, &MyHashItem[47]},
    /* 47 */ {"ACCESSKEY", FUNCNAME_accessKey, NULL},
    /* 48 */ {"ABORT", FUNCNAME_quitfm, NULL},
    /* 49 */ {"MENU", FUNCNAME_mainMn, NULL},
    /* 50 */ {"EXIT", FUNCNAME_quitfm, NULL},
    /* 51 */ {"PREV_HALF_PAGE", FUNCNAME_hpgBack, &MyHashItem[52]},
    /* 52 */ {"LINE_INFO", FUNCNAME_curlno, &MyHashItem[53]},
    /* 53 */ {"ADD_BOOKMARK", FUNCNAME_adBmark, NULL},
    /* 54 */ {"WHEREIS", FUNCNAME_srchfor, &MyHashItem[55]},
    /* 55 */ {"SELECT_MENU", FUNCNAME_selMn, &MyHashItem[56]},
    /* 56 */ {"GOTO_LINE", FUNCNAME_goLine, NULL},
    /* 57 */ {"MOUSE", FUNCNAME_mouse, NULL},
    /* 58 */ {"PIPE_BUF", FUNCNAME_pipeBuf, &MyHashItem[59]},
    /* 59 */ {"LINK_BEGIN", FUNCNAME_topA, NULL},
    /* 60 */ {"PEEK_IMG", FUNCNAME_peekIMG, NULL},
    /* 61 */ {"CHARSET", FUNCNAME_docCSet, NULL},
    /* 62 */ {"GOTO_LINK", FUNCNAME_followA, &MyHashItem[63]},
    /* 63 */ {"EXTERN_LINK", FUNCNAME_linkbrz, NULL},
    /* 64 */ {"MARK_WORD", FUNCNAME_chkWORD, NULL},
    /* 65 */ {"MOVE_LIST_MENU", FUNCNAME_movlistMn, &MyHashItem[66]},
    /* 66 */ {"LINK_MENU", FUNCNAME_linkMn, &MyHashItem[67]},
    /* 67 */ {"CURSOR_MIDDLE", FUNCNAME_cursorMiddle, NULL},
    /* 68 */ {"CURSOR_TOP", FUNCNAME_cursorTop, NULL},
    /* 69 */ {"REDO", FUNCNAME_redoPos, &MyHashItem[70]},
    /* 70 */ {"BOOKMARK", FUNCNAME_ldBmark, NULL},
    /* 71 */ {"NEXT_RIGHT_DOWN", FUNCNAME_nextRD, &MyHashItem[72]},
    /* 72 */ {"NEXT_LEFT", FUNCNAME_nextL, &MyHashItem[73]},
    /* 73 */ {"COMMAND", FUNCNAME_execCmd, &MyHashItem[74]},
    /* 74 */ {"@@@", FUNCNAME_nulcmd, NULL},
    /* 75 */ {"RESHAPE", FUNCNAME_reshape, &MyHashItem[76]},
    /* 76 */ {"ALARM", FUNCNAME_setAlarm, NULL},
    /* 77 */ {"UP", FUNCNAME_lup1, &MyHashItem[78]},
    /* 78 */ {"SETENV", FUNCNAME_setEnv, &MyHashItem[79]},
    /* 79 */ {"RELOAD", FUNCNAME_reload, &MyHashItem[80]},
    /* 80 */ {"LIST", FUNCNAME_linkLst, NULL},
    /* 81 */ {"NEXT_PAGE", FUNCNAME_pgFore, &MyHashItem[82]},
    /* 82 */ {"MOVE_MOUSE", FUNCNAME_movMs, &MyHashItem[83]},
    /* 83 */ {"DISPLAY_IMAGE", FUNCNAME_dispI, NULL},
    /* 84 */ {"TAB_LEFT", FUNCNAME_tabL, &MyHashItem[85]},
    /* 85 */ {"PIPE_SHELL", FUNCNAME_pipesh, &MyHashItem[86]},
    /* 86 */ {"NEXT_TAB", FUNCNAME_nextT, &MyHashItem[87]},
    /* 87 */ {"NEXT_DOWN", FUNCNAME_nextD, NULL},
    /* 88 */ {"MAIN_MENU", FUNCNAME_mainMn, &MyHashItem[89]},
    /* 89 */ {"LIST_MENU", FUNCNAME_listMn, NULL},
    /* 90 */ {"REINIT", FUNCNAME_reinit, &MyHashItem[91]},
    /* 91 */ {"EDIT", FUNCNAME_editBf, NULL},
    /* 92 */ {"SAVE_IMAGE", FUNCNAME_svI, &MyHashItem[93]},
    /* 93 */ {"NEXT_MARK", FUNCNAME_nextMk, &MyHashItem[94]},
    /* 94 */ {"COOKIE", FUNCNAME_cooLst, NULL},
    /* 95 */ {"LINK_END", FUNCNAME_lastA, &MyHashItem[96]},
    /* 96 */ {"LINE_BEGIN", FUNCNAME_linbeg, &MyHashItem[97]},
    /* 97 */ {"DELETE_PREVBUF", FUNCNAME_deletePrevBuf, NULL},
    /* 98 */ {"WRAP_TOGGLE", FUNCNAME_wrapToggle, NULL},
    /* 99 */ {"DEFAULT_CHARSET", FUNCNAME_defCSet, NULL},
    /* 100 */ {"NOTHING", FUNCNAME_nulcmd, &MyHashItem[101]},
    /* 101 */ {"FRAME", FUNCNAME_rFrame, NULL},
    /* 102 */ {"SEARCH_PREV", FUNCNAME_srchprv, &MyHashItem[103]},
    /* 103 */ {"NEXT", FUNCNAME_nextBf, &MyHashItem[104]},
    /* 104 */ {"LINE_END", FUNCNAME_linend, NULL},
    /* 105 */ {"SELECT", FUNCNAME_selBuf, NULL},
    /* 106 */ {"PREV_TAB", FUNCNAME_prevT, &MyHashItem[107]},
    /* 107 */ {"MOVE_LEFT", FUNCNAME_movL, NULL},
    /* 108 */ {"SEARCH_BACK", FUNCNAME_srchbak, &MyHashItem[109]},
    /* 109 */ {"SAVE", FUNCNAME_svSrc, NULL},
    /* 110 */ {"NEXT_HALF_PAGE", FUNCNAME_hpgFore, NULL},
    /* 111 */ {"SHIFT_LEFT", FUNCNAME_shiftl, &MyHashItem[112]},
    /* 112 */ {"READ_SHELL", FUNCNAME_readsh, &MyHashItem[113]},
    /* 113 */ {"PRINT", FUNCNAME_svBuf, &MyHashItem[114]},
    /* 114 */ {"MOVE_DOWN", FUNCNAME_movD, &MyHashItem[115]},
    /* 115 */ {"EDIT_SCREEN", FUNCNAME_editScr, NULL},
    /* 116 */ {"ISEARCH_BACK", FUNCNAME_isrchbak, NULL},
    /* 117 */ {"NEXT_LINK", FUNCNAME_nextA, NULL},
    /* 118 */ {"MSGS", FUNCNAME_msgs, NULL},
    /* 119 */ {"MULTIMAP", FUNCNAME_multimap, &MyHashItem[120]},
    /* 120 */ {"CENTER_H", FUNCNAME_ctrCsrH, NULL},
    /* 121 */ {"TAB_LINK", FUNCNAME_tabA, &MyHashItem[122]},
    /* 122 */ {"TAB_GOTO", FUNCNAME_tabURL, &MyHashItem[123]},
    /* 123 */ {"PREV_PAGE", FUNCNAME_pgBack, NULL},
    /* 124 */ {"SAVE_SCREEN", FUNCNAME_svBuf, NULL},
    /* 125 */ {"TAB_MENU", FUNCNAME_tabMn, &MyHashItem[126]},
    /* 126 */ {"SEARCH_FORE", FUNCNAME_srchfor, &MyHashItem[127]},
    /* 127 */ {"MOVE_UP1", FUNCNAME_movU1, &MyHashItem[128]},
    /* 128 */ {"MOVE_LEFT1", FUNCNAME_movL1, NULL},
    /* 129 */ {"PREV_MARK", FUNCNAME_prevMk, &MyHashItem[130]},
    /* 130 */ {"PEEK_LINK", FUNCNAME_peekURL, NULL},
    /* 131 */ {"MARK_URL", FUNCNAME_chkURL, NULL},
    /* 132 */ {"GOTO_RELATIVE", FUNCNAME_gorURL, NULL},
    /* 133 */ {"SUBMIT", FUNCNAME_submitForm, NULL},
    /* 134 */ {"NEXT_WORD", FUNCNAME_movRW, &MyHashItem[135]},
    /* 135 */ {"NEW_TAB", FUNCNAME_newT, &MyHashItem[136]},
    /* 136 */ {"HELP", FUNCNAME_ldhelp, NULL},
    /* 137 */ {"MOVE_DOWN1", FUNCNAME_movD1, NULL},
    /* 138 */ {"ISEARCH", FUNCNAME_isrchfor, NULL},
    /* 139 */ {"NEXT_RIGHT", FUNCNAME_nextR, &MyHashItem[140]},
    /* 140 */ {"CLOSE_TAB", FUNCNAME_closeT, &MyHashItem[141]},
    /* 141 */ {"CENTER_V", FUNCNAME_ctrCsrV, NULL},
    /* 142 */ {"MOVE_RIGHT1", FUNCNAME_movR1, NULL},
    /* 143 */ {"ESCMAP", FUNCNAME_escmap, &MyHashItem[144]},
    /* 144 */ {"ESCBMAP", FUNCNAME_escbmap, NULL},
    /* 145 */ {"MENU_MOUSE", FUNCNAME_menuMs, NULL},
    /* 146 */ {"PREV", FUNCNAME_prevBf, &MyHashItem[147]},
    /* 147 */ {"NULL", FUNCNAME_nulcmd, &MyHashItem[148]},
    /* 148 */ {"LINK_N", FUNCNAME_nthA, &MyHashItem[149]},
    /* 149 */ {"DICT_WORD", FUNCNAME_dictword, NULL},
    /* 150 */ {"PREV_LINK", FUNCNAME_prevA, &MyHashItem[151]},
    /* 151 */ {"CURSOR_BOTTOM", FUNCNAME_cursorBottom, NULL},
    /* 152 */ {"TAB_RIGHT", FUNCNAME_tabR, NULL},
    /* 153 */ {"MOUSE_TOGGLE", FUNCNAME_msToggle, &MyHashItem[154]},
    /* 154 */ {"BACK", FUNCNAME_backBf, NULL},
    /* 155 */ {"OPTIONS", FUNCNAME_ldOpt, &MyHashItem[156]},
    /* 156 */ {"DEFINE_KEY", FUNCNAME_defKey, NULL},
};

static HashItem_si *MyHashItemTbl[] = {
    &MyHashItem[0],
    NULL,
    NULL,
    NULL,
    NULL,
    &MyHashItem[3],
    &MyHashItem[4],
    &MyHashItem[6],
    &MyHashItem[7],
    &MyHashItem[12],
    &MyHashItem[13],
    &MyHashItem[14],
    &MyHashItem[15],
    &MyHashItem[16],
    &MyHashItem[17],
    &MyHashItem[22],
    &MyHashItem[25],
    &MyHashItem[27],
    &MyHashItem[28],
    &MyHashItem[30],
    &MyHashItem[31],
    NULL,
    &MyHashItem[32],
    NULL,
    &MyHashItem[34],
    NULL,
    NULL,
    &MyHashItem[35],
    &MyHashItem[39],
    &MyHashItem[41],
    &MyHashItem[42],
    &MyHashItem[43],
    &MyHashItem[48],
    &MyHashItem[49],
    &MyHashItem[50],
    &MyHashItem[51],
    NULL,
    &MyHashItem[54],
    NULL,
    &MyHashItem[57],
    &MyHashItem[58],
    &MyHashItem[60],
    &MyHashItem[61],
    &MyHashItem[62],
    &MyHashItem[64],
    &MyHashItem[65],
    &MyHashItem[68],
    &MyHashItem[69],
    &MyHashItem[71],
    &MyHashItem[75],
    &MyHashItem[77],
    &MyHashItem[81],
    &MyHashItem[84],
    &MyHashItem[88],
    &MyHashItem[90],
    &MyHashItem[92],
    &MyHashItem[95],
    &MyHashItem[98],
    &MyHashItem[99],
    &MyHashItem[100],
    &MyHashItem[102],
    NULL,
    &MyHashItem[105],
    NULL,
    &MyHashItem[106],
    &MyHashItem[108],
    NULL,
    &MyHashItem[110],
    &MyHashItem[111],
    &MyHashItem[116],
    NULL,
    &MyHashItem[117],
    NULL,
    &MyHashItem[118],
    &MyHashItem[119],
    &MyHashItem[121],
    &MyHashItem[124],
    &MyHashItem[125],
    NULL,
    &MyHashItem[129],
    &MyHashItem[131],
    &MyHashItem[132],
    &MyHashItem[133],
    NULL,
    &MyHashItem[134],
    &MyHashItem[137],
    &MyHashItem[138],
    NULL,
    &MyHashItem[139],
    &MyHashItem[142],
    &MyHashItem[143],
    &MyHashItem[145],
    &MyHashItem[146],
    NULL,
    NULL,
    &MyHashItem[150],
    &MyHashItem[152],
    &MyHashItem[153],
    NULL,
    &MyHashItem[155],
};

Hash_si functable = { 100, MyHashItemTbl };
