#pragma once
#include <stdint.h>

extern int LINES;
extern int COLS;
extern int Tabstop;
extern int IndentIncr;
extern int ShowEffect;
extern int PagerMax;
extern char SearchHeader;
extern const char* DefaultType;
extern char RenderFrame;
extern char TargetSelf;
extern char PermitSaveToPipe;
extern char DecodeCTE;
extern char AutoUncompress;
extern char PreserveTimestamp;
extern char ArgvIsURL;
extern char MetaRefresh;
extern char LocalhostOnly;
extern const char* HostName;
extern char fmInitialized;
extern char QuietMessage;
extern char TrapSignal;
extern const char* HTTP_proxy;
extern const char* HTTPS_proxy;
extern const char* GOPHER_proxy;
extern const char* FTP_proxy;
extern const char* NO_proxy;
extern int NOproxy_netaddr;
extern int DNS_order;
extern char NoCache;
extern char use_proxy;
extern int Do_not_use_ti_te;
extern const char* NNTP_server;
extern const char* NNTP_mode;
extern int MaxNewsMessage;
extern const char* document_root;
extern const char* personal_document_root;
extern const char* cgi_bin;
extern const char* index_file;
extern const char* CurrentDir;
extern int CurrentPid;
extern int open_tab_blank;
extern int open_tab_dl_list;
extern int close_tab_back;
extern int nTab;
extern int TabCols;
extern int CurrentKey;
extern const char* CurrentKeyData;
extern const char* CurrentCmdData;
extern const char* w3m_reqlog;
extern const char* w3m_version;
extern int enable_inline_image;
extern int w3m_debug;
extern int w3m_dump;
extern int w3m_halfload;
extern int override_content_type;
extern int override_user_agent;
extern int useColor;
extern int highIntensityColors;
extern int basic_color;
extern int anchor_color;
extern int image_color;
extern int form_color;
extern int bg_color;
extern int mark_color;
extern int useActiveColor;
extern int active_color;
extern int useVisitedColor;
extern int visited_color;
extern int confirm_on_quit;
extern int use_mark;
extern int emacs_like_lineedit;
extern int space_autocomplete;
extern int vi_prec_num;
extern int label_topline;
extern int nextpage_topline;
extern const char* displayTitleTerm;
extern int displayLink;
extern int displayLinkNumber;
extern int displayLineInfo;
extern int DecodeURL;
extern int retryAsHttp;
extern int showLineNum;
extern int show_srch_str;
extern const char* Imgdisplay;
extern int activeImage;
extern int displayImage;
extern int autoImage;
extern int useExtImageViewer;
extern int maxLoadImage;
extern int image_map_list;
extern int pseudoInlines;
extern const char* Editor;
extern const char* Mailer;
extern int MailtoOptions;
extern const char* ExtBrowser;
extern const char* ExtBrowser2;
extern const char* ExtBrowser3;
extern const char* ExtBrowser4;
extern const char* ExtBrowser5;
extern const char* ExtBrowser6;
extern const char* ExtBrowser7;
extern const char* ExtBrowser8;
extern const char* ExtBrowser9;
extern int BackgroundExtViewer;
extern int disable_secret_security_check;
extern const char* passwd_file;
extern const char* pre_form_file;
extern const char* siteconf_file;
extern const char* ftppasswd;
extern int ftppass_hostnamegen;
extern int do_download;
extern const char* image_source;
extern const char* UserAgent;
extern int NoSendReferer;
extern int CrossOriginReferer;
extern const char* AcceptLang;
extern const char* AcceptEncoding;
extern const char* AcceptMedia;
extern int WrapDefault;
extern int IgnoreCase;
extern int WrapSearch;
extern int squeezeBlankLine;
extern const char* BookmarkFile;
extern int UseExternalDirBuffer;
extern const char* DirBufferCommand;
extern int UseDictCommand;
extern const char* DictCommand;
extern int ignore_null_img_alt;
extern int displayInsDel;
extern int FoldTextarea;
extern int FoldLine;
extern int DefaultURLString;
extern int MarkAllPages;
extern const char* CGIBIN_DIR;
extern const char* AUXBIN_DIR;
extern const char* HELP_DIR;
extern const char* ETC_DIR;
extern const char* CONF_DIR;
extern const char* RC_DIR;
extern const char* mailcap_files;
extern const char* mimetypes_files;
extern int UseHistory;
extern int URLHistSize;
extern int SaveURLHist;
extern int multicolList;
extern char ExtHalfdump;
extern char FollowLocale;
extern char UseContentCharset;
extern char SearchConv;
extern char SimplePreserveSpace;
extern char UseAltEntity;
extern char UseGraphicChar;
extern char DisplayBorders;
extern char DisableCenter;
extern int no_rc_dir;
extern const char* rc_dir;
extern const char* tmp_dir;
extern const char* param_tmp_dir;
extern const char* mkd_tmp_dir;
extern const char* config_file;
extern int default_use_cookie;
extern int use_cookie;
extern int show_cookie;
extern int accept_cookie;
extern int accept_bad_cookie;
extern const char* cookie_reject_domains;
extern const char* cookie_accept_domains;
extern const char* cookie_avoid_wrong_number_of_dots;
extern int view_unseenobject;
extern int ssl_verify_server;
extern const char* ssl_cert_file;
extern const char* ssl_key_file;
extern const char* ssl_ca_path;
extern const char* ssl_ca_file;
extern int ssl_ca_default;
extern int ssl_path_modified;
extern const char* ssl_min_version;
extern int is_redisplay;
extern int clear_buffer;
extern double pixel_per_char;
extern int pixel_per_char_i;
extern int set_pixel_per_char;
extern double pixel_per_line;
extern int pixel_per_line_i;
extern int set_pixel_per_line;
extern double image_scale;
extern int use_lessopen;
extern const char* keymap_file;
extern int FollowRedirection;
extern int w3m_backend;
extern const char* ssl_forbid_method;
extern const char* ssl_cipher;
extern const char* SearchString;
extern const char* MarkString;
