#include "defun_impl.h"

const char* GlobalKeymap[128] = {
    /*  C-@     C-a     C-b     C-c     C-d     C-e     C-f     C-g      */
    "MARK",
    "LINE_BEGIN",
    "MOVE_LEFT",
    "NOTHING",
    "NOTHING",
    "LINE_END",
    "MOVE_RIGHT",
    "LINE_INFO",
    /*  C-h     C-i     C-j     C-k     C-l     C-m     C-n     C-o      */
    "HISTORY",
    "NEXT_LINK",
    "GOTO_LINK",
    "COOKIE",
    "REDRAW",
    "GOTO_LINK",
    "MOVE_DOWN",
    "NOTHING",
    /*  C-p     C-q     C-r     C-s     C-t     C-u     C-v     C-w      */
    "MOVE_UP",
    "CLOSE_TAB",
    "ISEARCH_BACK",
    "ISEARCH",
    "TAB_LINK",
    "PREV_LINK",
    "NEXT_PAGE",
    "WRAP_TOGGLE",
    /*  C-x     C-y     C-z     C-[     C-\     C-]     C-^     C-_      */
    "NOTHING",
    "NOTHING",
    "SUSPEND",
    "ESCMAP",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "GOTO_HOME",
    /*  SPC     !       "       #       $       %       &       '        */
    "NEXT_PAGE",
    "SHELL",
    "REG_MARK",
    "PIPE_SHELL",
    "LINE_END",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    /*  (       )       *       +       ,       -       .       /        */
    "UNDO",
    "REDO",
    "NOTHING",
    "NEXT_PAGE",
    "LEFT",
    "PREV_PAGE",
    "RIGHT",
    "SEARCH",
    /*  0       1       2       3       4       5       6       7        */
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    /*  8       9       :       ;       <       =       >       ?        */
    "NOTHING",
    "NOTHING",
    "MARK_URL",
    "MARK_WORD",
    "SHIFT_LEFT",
    "INFO",
    "SHIFT_RIGHT",
    "SEARCH_BACK",
    /*  @       A       B       C       D       E       F       G        */
    "READ_SHELL",
    "NOTHING",
    "BACK",
    "NOTHING",
    "DOWNLOAD_LIST",
    "EDIT",
    "FRAME",
    "END",
    /*  H       I       J       K       L       M       N       O        */
    "HELP",
    "VIEW_IMAGE",
    "UP",
    "DOWN",
    "LIST",
    "EXTERN",
    "SEARCH_PREV",
    "NOTHING",
    /*  P       Q       R       S       T       U       V       W        */
    "NOTHING",
    "ABORT",
    "RELOAD",
    "PRINT",
    "NEW_TAB",
    "GOTO",
    "LOAD",
    "PREV_WORD",
    /*  X       Y       Z       [       \       ]       ^       _        */
    "NOTHING",
    "NOTHING",
    "CENTER_H",
    "LINK_BEGIN",
    "NOTHING",
    "LINK_END",
    "LINE_BEGIN",
    "NOTHING",
    /*  `       a       b       c       d       e       f       g        */
    "NOTHING",
    "SAVE_LINK",
    "PREV_PAGE",
    "PEEK",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "BEGIN",
    /*  h       i       j       k       l       m       n       o        */
    "MOVE_LEFT",
    "PEEK_IMG",
    "MOVE_DOWN",
    "MOVE_UP",
    "MOVE_RIGHT",
    "MOUSE_TOGGLE",
    "SEARCH_NEXT",
    "OPTIONS",
    /*  p       q       r       s       t       u       v       w        */
    "NOTHING",
    "QUIT",
    "VERSION",
    "SELECT_MENU",
    "NOTHING",
    "PEEK_LINK",
    "SOURCE",
    "NEXT_WORD",
    /*  x       y       z       {       |       }       ~       DEL      */
    "NOTHING",
    "NOTHING",
    "CENTER_V",
    "PREV_TAB",
    "PIPE_BUF",
    "NEXT_TAB",
    "NOTHING",
    "NOTHING",
};

const char* EscKeymap[128] = {
    /*  C-@     C-a     C-b     C-c     C-d     C-e     C-f     C-g      */
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    /*  C-h     C-i     C-j     C-k     C-l     C-m     C-n     C-o      */
    "NOTHING",
    "PREV_LINK",
    "SAVE_LINK",
    "NOTHING",
    "NOTHING",
    "SAVE_LINK",
    "NOTHING",
    "NOTHING",
    /*  C-p     C-q     C-r     C-s     C-t     C-u     C-v     C-w      */
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    /*  C-x     C-y     C-z     C-[     C-\     C-]     C-^     C-_      */
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    /*  SPC     !       "       #       $       %       &       '        */
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    /*  (       )       *       +       ,       -       .       /        */
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    /*  0       1       2       3       4       5       6       7        */
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    /*  8       9       :       ;       <       =       >       ?        */
    "NOTHING",
    "NOTHING",
    "MARK_MID",
    "NOTHING",
    "BEGIN",
    "NOTHING",
    "END",
    "NOTHING",
    /*  @       A       B       C       D       E       F       G        */
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    /*  H       I       J       K       L       M       N       O        */
    "NOTHING",
    "SAVE_IMAGE",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "EXTERN_LINK",
    "NOTHING",
    "ESCBMAP",
    /*  P       Q       R       S       T       U       V       W        */
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "DICT_WORD_AT",
    /*  X       Y       Z       [       \       ]       ^       _        */
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "ESCBMAP",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    /*  `       a       b       c       d       e       f       g        */
    "NOTHING",
    "ADD_BOOKMARK",
    "BOOKMARK",
    "COMMAND",
    "NOTHING",
    "EDIT_SCREEN",
    "NOTHING",
    "GOTO_LINE",
    /*  h       i       j       k       l       m       n       o        */
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "DEFINE_KEY",
    "LIST_MENU",
    "MOVE_LIST_MENU",
    "NEXT_MARK",
    "SET_OPTION",
    /*  p       q       r       s       t       u       v       w        */
    "PREV_MARK",
    "NOTHING",
    "NOTHING",
    "SAVE",
    "TAB_MENU",
    "GOTO_RELATIVE",
    "PREV_PAGE",
    "DICT_WORD",
    /*  x       y       z       {       |       }       ~       DEL      */
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
};

const char* EscBKeymap[128] = {
    /*  C-@     C-a     C-b     C-c     C-d     C-e     C-f     C-g      */
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    /*  C-h     C-i     C-j     C-k     C-l     C-m     C-n     C-o      */
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    /*  C-p     C-q     C-r     C-s     C-t     C-u     C-v     C-w      */
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    /*  C-x     C-y     C-z     C-[     C-\     C-]     C-^     C-_      */
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    /*  SPC     !       "       #       $       %       &       '        */
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    /*  (       )       *       +       ,       -       .       /        */
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    /*  0       1       2       3       4       5       6       7        */
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    /*  8       9       :       ;       <       =       >       ?        */
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "SGRMOUSE",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    /*  @       A       B       C       D       E       F       G        */
    "NOTHING",
    "MOVE_UP",
    "MOVE_DOWN",
    "MOVE_RIGHT",
    "MOVE_LEFT",
    "NOTHING",
    "END",
    "NEXT_PAGE",
    /*  H       I       J       K       L       M       N       O        */
    "BEGIN",
    "PREV_PAGE",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "MOUSE",
    "NOTHING",
    "NOTHING",
    /*  P       Q       R       S       T       U       V       W        */
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    /*  X       Y       Z       [       \       ]       ^       _        */
    "NOTHING",
    "NOTHING",
    "PREV_LINK",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    /*  `       a       b       c       d       e       f       g        */
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    /*  h       i       j       k       l       m       n       o        */
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    /*  p       q       r       s       t       u       v       w        */
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    /*  x       y       z       {       |       }       ~       DEL      */
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
};

const char* EscDKeymap[128] = {
    /*  0       1       INS     3       4       PgUp,   PgDn    7        */
    "NOTHING",
    "BEGIN",
    "MENU",
    "NOTHING",
    "END",
    "PREV_PAGE",
    "NEXT_PAGE",
    "NOTHING",
    /*  8       9       10      F1      F2      F3      F4      F5       */
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    /*  16      F6      F7      F8      F9      F10     22      23       */
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    /*  24      25      26      27      HELP    29      30      31       */
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "MENU",
    "NOTHING",
    "NOTHING",
    "NOTHING",

    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",

    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",

    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
    "NOTHING",
};
