#include "w3m_types.h"
#include "cookie.h"
#include "image.h"

#define PAGER_MAX_LINE 10000 /* Maximum line kept as pager */

struct Runtime g_runtime = {
    .NO_proxy_domains = NULL,

    .CurrentDir = 0,
    .CurrentPid = 0,
    .fileToDelete = 0,
    .tmp_dir = 0,

    .OptionCharset = WC_CES_US_ASCII,
    .OptionEncode = false,

    .view_unseenobject = (false),
    .is_redisplay = (false),
    .clear_buffer = (true),
    .image_scale = (100),
    .keymap_file = (KEYMAP_FILE),
    .FollowRedirection = (10),
    .w3m_backend = (false),
    .multicolList = (false),
    .FollowLocale = (true),
    .UseContentCharset = (true),
    .SearchConv = (true),
    .SimplePreserveSpace = (false),
    .UseAltEntity = (false),
    .DisplayBorders = (false),
    .DisableCenter = (false),
    .no_rc_dir = (false),
    .rc_dir = (NULL),
    .param_tmp_dir = (NULL),
    .mkd_tmp_dir = (NULL),
    .config_file = (NULL),
    .default_use_cookie = (true),
    .use_cookie = (true),
    .show_cookie = (false),
    .accept_cookie = (true),
    .accept_bad_cookie = (ACCEPT_BAD_COOKIE_DISCARD),
    .cookie_reject_domains = (NULL),
    .cookie_accept_domains = (NULL),
    .cookie_avoid_wrong_number_of_dots = (NULL),
    .w3m_dump = (0),
    .header_string = (NULL),
    .override_content_type = (false),
    .override_user_agent = (false),
    .confirm_on_quit = (true),
    .use_mark = (false),
    .vi_prec_num = (false),
    .label_topline = (false),
    .nextpage_topline = (false),
    .displayTitleTerm = (NULL),
    .displayLinkNumber = (false),
    .retryAsHttp = (true),
    .show_srch_str = (true),
    .Imgdisplay = (IMGDISPLAY),
    .autoImage = (true),
    .useExtImageViewer = (true),
    .maxLoadImage = (4),
    .image_map_list = (true),
    .pseudoInlines = (true),
    .Editor = (DEF_EDITOR),
    .Mailer = (DEF_MAILER),
    .MailtoOptions = (MAILTO_OPTIONS_IGNORE),
    .ExtBrowser = (DEF_EXT_BROWSER),
    .ExtBrowser2 = (NULL),
    .ExtBrowser3 = (NULL),
    .ExtBrowser4 = (NULL),
    .ExtBrowser5 = (NULL),
    .ExtBrowser6 = (NULL),
    .ExtBrowser7 = (NULL),
    .ExtBrowser8 = (NULL),
    .ExtBrowser9 = (NULL),
    .BackgroundExtViewer = (true),
    .disable_secret_security_check = (false),
    .passwd_file = (PASSWD_FILE),
    .pre_form_file = (PRE_FORM_FILE),
    .ftppasswd = (NULL),
    .ftppass_hostnamegen = (true),
    .UserAgent = (NULL),
    .NoSendReferer = (false),
    .CrossOriginReferer = (true),
    .AcceptLang = (NULL),
    .AcceptEncoding = (NULL),
    .AcceptMedia = (NULL),
    .WrapDefault = (false),
    .IgnoreCase = (true),
    .WrapSearch = (false),
    .squeezeBlankLine = (false),
    .BookmarkFile = (NULL),
    .UseExternalDirBuffer = (true),
    .DirBufferCommand = ("file:///$LIB/dirlist" CGI_EXTENSION),
    .UseDictCommand = (true),
    .DictCommand = ("file:///$LIB/w3mdict" CGI_EXTENSION),
    .ignore_null_img_alt = (true),
    .displayInsDel = (DISPLAY_INS_DEL_NORMAL),
    .FoldTextarea = (false),
    .DefaultURLString = (DEFAULT_URL_CURRENT),
    .MarkAllPages = (false),
    .mailcap_files = (USER_MAILCAP ", " SYS_MAILCAP),
    .mimetypes_files = (USER_MIMETYPES ", " SYS_MIMETYPES),
    .urimethodmap_files = (USER_URIMETHODMAP ", " SYS_URIMETHODMAP),
    .open_tab_blank = (false),
    .open_tab_dl_list = (false),
    .close_tab_back = (false),
    .TabCols = (10),
    .DNS_order = (DNS_ORDER_UNSPEC),
    .NoCache = (false),
    .use_proxy = (true),
    .document_root = (NULL),
    .personal_document_root = (NULL),
    .cgi_bin = (NULL),
    .index_file = (NULL),
    .HTTP_proxy = (NULL),
    .HTTPS_proxy = (NULL),
    .FTP_proxy = (NULL),
    .NO_proxy = (NULL),
    .NOproxy_netaddr = (true),
    .IndentIncr = (4),
    .PagerMax = (PAGER_MAX_LINE),
    .DefaultType = (NULL),
    .RenderFrame = (false),
    .TargetSelf = (false),
    .PermitSaveToPipe = (false),
    .AutoUncompress = (false),
    .PreserveTimestamp = (true),
    .ArgvIsURL = (true),
    .MetaRefresh = (false),
    .LocalhostOnly = (false),
    .HostName = (NULL),
    .TrapSignal = (true),

    .ssl_verify_server = true,
    .ssl_cert_file = NULL,
    .ssl_key_file = NULL,
    .ssl_ca_path = NULL,
    .ssl_ca_file = DEF_CAFILE,
    .ssl_ca_default = true,
    .ssl_path_modified = false,
    .ssl_forbid_method = "2, 3, t, 5",
    .ssl_min_version = NULL,
    .ssl_cipher = NULL,

    .DecodeURL = (false),
    .QuietMessage = (false),
    .ShowEffect = (true),
    .displayLink = (false),
    .useColor = (true),
    .displayImage = (true),
    .displayLineInfo = (false),
    .activeImage = (false),
    .pixel_per_char = (DEFAULT_PIXEL_PER_CHAR),
    .pixel_per_char_i = (DEFAULT_PIXEL_PER_CHAR),
    .set_pixel_per_char = (false),
    .pixel_per_line = (DEFAULT_PIXEL_PER_LINE),
    .pixel_per_line_i = (DEFAULT_PIXEL_PER_LINE),
    .set_pixel_per_line = (false),
    .basic_color = (8), /* don't change */
    .anchor_color = (4), /* blue  */
    .image_color = (2), /* green */
    .form_color = (1), /* red   */
    .bg_color = (8), /* don't change */
    .mark_color = (6), /* cyan */
    .useActiveColor = (false),
    .active_color = (6), /* cyan */
    .useVisitedColor = (false),
    .visited_color = (5), /* magenta  */

    .space_autocomplete = (false),
    .emacs_like_lineedit = (false),

    // Don't change
    .InnerCharset = (WC_CES_WTF),

    .DisplayCharset = (DISPLAY_CHARSET),
    .DocumentCharset = (DOCUMENT_CHARSET),
    .SystemCharset = (SYSTEM_CHARSET),
    .BookmarkCharset = (SYSTEM_CHARSET),

    .ExtHalfdump = (false),
    .Tabstop = 8,
    .highIntensityColors = (false),

    .UseHistory = (true),
    .URLHistSize = (100),
    .SaveURLHist = (true),
    .LoadHist = 0,
    .SaveHist = 0,
    .URLHist = 0,
    .ShellHist = 0,
    .TextHist = 0,

    .lines = 0,
    .cols = 0,
    .Do_not_use_ti_te = false,

    .showLineNum = (false),
    .FoldLine = (false),

    .CurrentTab = 0,
    .FirstTab = 0,
    .LastTab = 0,
    .nTab = 0,

    .CurrentKey = -1,
    .CurrentKeyData = 0,
    .CurrentCmdData = 0,
    .prec_num = 0,
    .prev_key = -1,

    .CurrentEvent = 0,
    .LastEvent = 0,
};
