image: alpine/edge
sources:
  - https://git.sr.ht/~rkta/w3m
packages:
  - ed
  - gc-dev
  - gpm-dev
  - imlib2-dev
  - libbsd-dev
  - libressl-dev
  - linux-headers
  - ncurses-dev
  - perl
  - tcc
  - tcc-libs-static
triggers:
  - action: email
    condition: always
    to: mail@rkta.de
environment:
  NPROC: '8'
tasks:
  - default: |
      cd w3m
      t/build default

  - debian: |
      cd w3m
      t/build debian

  - gdk-pixbuf: |
      cd w3m
      t/build gdk_pixbuf

  - disable: |
      cd w3m
      t/build disable

  - tcc: |
      cd w3m
      t/build tcc

  - lto: |
      cd w3m
      t/build lto
