image: netbsd/latest
sources:
  - https://git.sr.ht/~rkta/w3m
packages:
  - boehm-gc
  - gettext-tools
triggers:
  - action: email
    condition: always
    to: mail@rkta.de
environment:
  NPROC: '8'
  OPTS: '-Wl,-R/usr/pkg/lib'
tasks:
  - versions: |
      set +x
      for c in cc clang gcc tcc
      do
        $c -v >/dev/null 2>&1 || continue
        printf "%s:\t%s\n" $c "$(2>&1 $c -v | grep 'version ')"
      done
  - default: |
      cd w3m
      t/build default

  - netbsd: |
      cd w3m
      t/build netbsd

  - gdk-pixbuf: |
      cd w3m
      t/build gdk_pixbuf

  - disable: |
      cd w3m
      t/build disable
