image: netbsd/latest
sources:
  - https://git.sr.ht/~rkta/w3m
packages:
  - boehm-gc
  - gettext-tools
triggers:
  - action: email
    condition: always
    to: mail@rkta.de
environment:
  OPTS: '-Werror'
  LD_LIBRARY_PATH: '/usr/pkg/lib'
tasks:
  - default: |
      cd w3m
      make distclean || :
      ./configure --with-gc=/usr/pkg
      make -j4
      test -x w3m
      cd t
      sh run

  - netbsd: |
      cd w3m
      make distclean || :
      ./configure --with-gc=/usr/pkg \
        --disable-messagel10n \
        --disable-help_cgi \
        --enable-color \
        --enable-cookie \
        --enable-m17n \
        --enable-mouse \
        --enable-unicode \
        --with-browser= \
        --with-termlib \
        --with-editor=vi
      make -j4
      test -x w3m
      cd t
      sh run

  - gdk-pixbuf: |
      cd w3m
      make distclean || :
      ./configure --with-gc=/usr/pkg \
        --disable-messagel10n \
        --disable-help_cgi \
        --enable-color \
        --enable-cookie \
        --enable-m17n \
        --enable-mouse \
        --enable-unicode \
        --with-browser= \
        --with-termlib \
        --with-editor=vi \
        --with-imagelib=gdk-pixbuf
      make -j4
      test -x w3m
      cd t
      sh run

  - disable: |
      cd w3m
      make distclean || :
      ./configure --with-gc=/usr/pkg \
        --disable-alarm \
        --disable-color\
        --disable-cookie \
        --disable-dict \
        --disable-external_uri_loader \
        --disable-gopher \
        --disable-history \
        --disable-image \
        --disable-ipv6 \
        --disable-m17n \
        --disable-menu \
        --disable-mouse \
        --disable-nls \
        --disable-nntp \
        --disable-sslverify \
        --disable-unicode \
        --disable-w3mmailer \
        --without-ssl
      make -j4
      test -x w3m
