#!/bin/sh

# Build and test multiple build configurations
# USAGE: build [conf]...

# Environment: OPTS and NPROC, see below.

# If the script is called without any arguments it will automagically collect
# all build configurations and run them all.

# Every build configuration is a function. Make sure the function name is at
# the start of the line and does only contain characters a-z and '_'. Function
# names starting with an underscore are utility functions and will not be
# collected.

export OPTS="-Werror $OPTS"
opts="$OPTS"
nproc=${NPROC:-1}

_die()
{
	>&2 printf "FAILED: Task: %s Step: %s\n" "$2" "$3"
	exit "$1"
}

debian()
{
	./configure \
		--enable-alarm \
		--enable-ansi_color \
		--enable-color \
		--enable-cookie \
		--enable-external_uri_loader \
		--enable-gopher \
		--enable-image \
		--enable-ipv6 \
		--enable-m17n \
		--enable-menu \
		--enable-mouse \
		--enable-nls \
		--enable-nntp \
		--enable-sslverify \
		--enable-unicode \
		--enable-w3mmailer \
		--with-imagelib=imlib2 \
		--with-migemo="cmigemo -q -d /usr/share/cmigemo/utf-8/migemo-dict" \
		--with-ssl
}

default()
{
	./configure
}

disable()
{
	./configure \
		--disable-alarm \
		--disable-color \
		--disable-cookie \
		--disable-dict \
		--disable-external_uri_loader \
		--disable-gopher \
		--disable-history \
		--disable-image \
		--disable-ipv6 \
		--disable-m17n \
		--disable-menu \
		--disable-mouse \
		--disable-nls \
		--disable-nntp \
		--disable-sslverify \
		--disable-unicode \
		--disable-w3mmailer \
		--without-ssl
}

gdk_pixbuf()
{
	./configure \
		--enable-alarm \
		--enable-ansi_color \
		--enable-color \
		--enable-cookie \
		--enable-external_uri_loader \
		--enable-gopher \
		--enable-image \
		--enable-ipv6 \
		--enable-m17n \
		--enable-menu \
		--enable-mouse \
		--enable-nls \
		--enable-nntp \
		--enable-sslverify \
		--enable-unicode \
		--enable-w3mmailer \
		--with-imagelib=gdk-pixbuf \
		--with-migemo="cmigemo -q -d /usr/share/cmigemo/utf-8/migemo-dict" \
		--with-ssl
}

lto()
{
	export OPTS="-flto $OPTS"
	./configure
}

netbsd()
{
	./configure \
		--disable-messagel10n \
		--disable-help_cgi \
		--enable-color \
		--enable-cookie \
		--enable-m17n \
		--enable-mouse \
		--enable-unicode \
		--with-browser= \
		--with-termlib \
		--with-editor=vi
}

tcc()
{
	CC=tcc ./configure \
		--enable-alarm \
		--enable-ansi_color \
		--enable-bgcolor \
		--enable-color \
		--enable-cookie \
		--enable-dict \
		--enable-digest_auth \
		--enable-external_uri_loader \
		--enable-gopher \
		--enable-help_cgi \
		--enable-history \
		--enable-image \
		--enable-ipv6 \
		--enable-japanese \
		--enable-keymap=w3m \
		--enable-m17n \
		--enable-menu \
		--enable-messagel10n \
		--enable-mouse \
		--enable-nls \
		--enable-nntp \
		--enable-sslverify \
		--enable-unicode \
		--enable-w3mmailer \
		--enable-xface \
		--with-browser \
		--with-editor \
		--with-imagelib=imlib2 \
		--with-mailer \
		--with-migemo="cmigemo -q -d /usr/share/cmigemo/utf-8/migemo-dict" \
		--with-ssl \
		--with-termlib \
		--with-x
}

# If no arguments were passed, get all the above function names (except _die)
# and drop the parentheses.
# shellcheck disable=SC2046
test "$1" || set -- $(sed -n '/^[a-z][a-z_]\{1,\}()$/s/()//p' "$0")

for conf
do
	export OPTS="$opts"
	make distclean || :
	$conf || _die "$?" "$conf" configure
	make -j"$nproc" || _die "$?" "$conf" make
	sh t/run || _die "$?" "$conf" tests
done
