#!/bin/sh

# Tests should be run from the tests directory
if ! test "$(basename "$PWD")" = "t"
then
	cd t || { >&2 printf "%s\n" "Cannot cd into test directory!"; exit 2; }
fi

# We need an executable
test -x ../w3m || { >&2 printf "%s\n" "No executable!";  exit 2; }

test "$1" || set -- [0-9][0-9][0-9][0-9]*

for t
do
	t=${t#t/}
	case "$t" in
		*.orig|*.rej)		continue ;;
		[0-9][0-9][0-9][0-9])	t="$(find . -name "$t"'*' \
						-not -name '*.orig' \
						-not -name '*.rej')" ;;
	esac
	./$t || { >&2 printf 'Test failed: %s\n' "$t"; exit 1; }
done
