/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Wed Feb 10 12:47:03 1999
 */

// extern void FUNC_NAME(void) from DEFUN

extern void nulcmd(void);
extern void pgFore(void);
extern void pgBack(void);
extern void hpgFore(void);
extern void hpgBack(void);
extern void lup1(void);
extern void ldown1(void);
extern void ctrCsrV(void);
extern void ctrCsrH(void);
extern void rdrwSc(void);
extern void srchfor(void);
extern void isrchfor(void);
extern void srchbak(void);
extern void isrchbak(void);
extern void srchnxt(void);
extern void srchprv(void);
extern void shiftl(void);
extern void shiftr(void);
extern void col1R(void);
extern void col1L(void);
extern void setEnv(void);
extern void pipeBuf(void);
extern void pipesh(void);
extern void readsh(void);
extern void execsh(void);
extern void ldfile(void);
extern void ldhelp(void);
extern void movL(void);
extern void movL1(void);
extern void movD(void);
extern void movD1(void);
extern void movU(void);
extern void movU1(void);
extern void movR(void);
extern void movR1(void);
extern void movLW(void);
extern void movRW(void);
extern void qquitfm(void);
extern void quitfm(void);
extern void selBuf(void);
extern void susp(void);
extern void goLine(void);
extern void goLineF(void);
extern void goLineL(void);
extern void linbeg(void);
extern void linend(void);
extern void editBf(void);
extern void editScr(void);
extern void followA(void);
extern void bufferA(void);
extern void followI(void);
extern void submitForm(void);
extern void followForm(void);
extern void topA(void);
extern void lastA(void);
extern void nthA(void);
extern void onA(void);

extern void nextA(void);
extern void prevA(void);
extern void nextVA(void);
extern void prevVA(void);
extern void nextL(void);
extern void nextLU(void);
extern void nextR(void);
extern void nextRD(void);
extern void nextD(void);
extern void nextU(void);
extern void nextBf(void);
extern void prevBf(void);
extern void backBf(void);
extern void deletePrevBuf(void);
extern void goURL(void);
extern void goHome(void);
extern void gorURL(void);
extern void ldBmark(void);
extern void adBmark(void);
extern void ldOpt(void);
extern void setOpt(void);
extern void pginfo(void);
extern void msgs(void);
extern void svA(void);
extern void svI(void);
extern void svBuf(void);
extern void svSrc(void);
extern void peekURL(void);
extern void peekIMG(void);
extern void curURL(void);
extern void vwSrc(void);
extern void reload(void);
extern void reshape(void);
extern void chkURL(void);
extern void chkWORD(void);
extern void extbrz(void);
extern void linkbrz(void);
extern void curlno(void);
extern void execCmd(void);
extern void dispI(void);
extern void stopI(void);
extern void setAlarm(void);
extern void reinit(void);
extern void defKey(void);
extern void newT(void);
extern void closeT(void);
extern void nextT(void);
extern void prevT(void);
extern void ldDL(void);
extern void linkLst(void);
extern void linkMn(void);
extern void accessKey(void);
extern void listMn(void);
extern void movlistMn(void);
extern void undoPos(void);
extern void redoPos(void);
extern void cursorTop(void);
extern void cursorMiddle(void);
extern void cursorBottom(void);

//
//
//
extern Buffer* loadGeneralFile(char* path, ParsedURL* current, char* referer, int flag, FormList* request);
extern int is_boundary(unsigned char*, unsigned char*);
extern int is_blank_line(char* line, int indent);
extern void push_render_image(Str str, int width, int limit,
    struct html_feed_environ* h_env);
extern void flushline(struct html_feed_environ* h_env, struct readbuffer* obuf,
    int indent, int force, int width);
extern void do_blankline(struct html_feed_environ* h_env,
    struct readbuffer* obuf, int indent, int indent_incr,
    int width);
extern void purgeline(struct html_feed_environ* h_env);
extern void save_fonteffect(struct html_feed_environ* h_env,
    struct readbuffer* obuf);
extern void restore_fonteffect(struct html_feed_environ* h_env,
    struct readbuffer* obuf);

extern Str process_img(struct parsed_tag* tag, int width);
extern Str process_anchor(struct parsed_tag* tag, char* tagbuf);
extern Str process_input(struct parsed_tag* tag);
extern Str process_button(struct parsed_tag* tag);
extern Str process_n_button(void);
extern Str process_select(struct parsed_tag* tag);
extern Str process_n_select(void);
extern void feed_select(char* str);
extern void process_option(void);
extern Str process_textarea(struct parsed_tag* tag, int width);
extern Str process_n_textarea(void);
extern void feed_textarea(char* str);
extern Str process_form(struct parsed_tag* tag);
extern Str process_n_form(void);
extern int getMetaRefreshParam(char* q, Str* refresh_uri);
extern int HTMLtagproc1(struct parsed_tag* tag,
    struct html_feed_environ* h_env);
extern void HTMLlineproc2(Buffer* buf, TextLineList* tl);
extern void HTMLlineproc0(char* istr, struct html_feed_environ* h_env,
    int internal);
#define HTMLlineproc1(x, y) HTMLlineproc0(x, y, TRUE)
extern char* convert_size(clen_t size, int usefloat);
extern char* convert_size2(clen_t size1, clen_t size2, int usefloat);
extern void showProgress(clen_t* linelen, clen_t* trbyte);
extern void init_henv(struct html_feed_environ*, struct readbuffer*,
    struct environment*, int, TextLineList*, int, int);
extern void completeHTMLstream(struct html_feed_environ*,
    struct readbuffer*);
extern Buffer* loadHTMLString(Str page);
extern void saveBuffer(Buffer* buf, FILE* f, int cont);
extern void saveBufferBody(Buffer* buf, FILE* f, int cont);
extern Buffer* getshell(char* cmd);
extern Buffer* getpipe(char* cmd);
extern Buffer* openPagerBuffer(InputStream stream, Buffer* buf);
extern Buffer* openGeneralPagerBuffer(InputStream stream);
extern int _doFileCopy(char* tmpf, char* defstr, int download);
#define doFileCopy(tmpf, defstr) _doFileCopy(tmpf, defstr, FALSE);
extern int doFileMove(char* tmpf, char* defstr);
extern int checkCopyFile(char* path1, char* path2);
extern int checkSaveFile(InputStream stream, char* path);
extern int checkOverWrite(char* path);
extern char* inputAnswer(char* prompt);
extern int matchattr(char* p, char* attr, int len, Str* value);
extern char* checkHeader(Buffer* buf, char* field);
extern void addDownloadList(pid_t pid, char* url, char* save, char* lock,
    clen_t size);
extern void stopDownload(void);
extern int checkDownloadList(void);
extern void download_action(struct parsed_tagarg* arg);
extern Buffer* newBuffer(int width);
extern Buffer* nullBuffer(void);
extern void clearBuffer(Buffer* buf);
extern void discardBuffer(Buffer* buf);
extern Buffer* namedBuffer(Buffer* first, char* name);
extern Buffer* deleteBuffer(Buffer* first, Buffer* delbuf);
extern Buffer* replaceBuffer(Buffer* first, Buffer* delbuf, Buffer* newbuf);
extern Buffer* nthBuffer(Buffer* firstbuf, int n);
extern void gotoRealLine(Buffer* buf, int n);
extern void gotoLine(Buffer* buf, int n);
extern Buffer* selectBuffer(Buffer* firstbuf, Buffer* currentbuf,
    char* selectchar);
extern void reshapeBuffer(Buffer* buf);
extern void copyBuffer(Buffer* a, Buffer* b);
extern Buffer* prevBuffer(Buffer* first, Buffer* buf);
extern int writeBufferCache(Buffer* buf);
extern int readBufferCache(Buffer* buf);
extern void addChar(char c, Lineprop mode);
extern void addMChar(char* c, Lineprop mode, size_t len);
extern void record_err_message(char* s);
extern Buffer* message_list_panel(void);
extern void message(char* s, int return_x, int return_y);
extern void disp_err_message(char* s, int redraw_current);
extern void disp_message_nsec(char* s, int redraw_current, int sec, int purge,
    int mouse);
extern void disp_message(char* s, int redraw_current);
#define disp_message_nomouse disp_message
extern void set_delayed_message(char* s);
extern void cursorUp0(Buffer* buf, int n);
extern void cursorUp(Buffer* buf, int n);
extern void cursorDown0(Buffer* buf, int n);
extern void cursorDown(Buffer* buf, int n);
extern void cursorUpDown(Buffer* buf, int n);
extern void cursorRight(Buffer* buf, int n);
extern void cursorLeft(Buffer* buf, int n);
extern void cursorHome(Buffer* buf);
extern void arrangeCursor(Buffer* buf);
extern void arrangeLine(Buffer* buf);
extern void cursorXY(Buffer* buf, int x, int y);
extern void restorePosition(Buffer* buf, Buffer* orig);
extern int columnSkip(Buffer* buf, int offset);
extern int columnPos(Line* line, int column);
extern int columnLen(Line* line, int column);
extern Line* lineSkip(Buffer* buf, Line* line, int offset, int last);
extern Line* currentLineSkip(Buffer* buf, Line* line, int offset, int last);
extern int gethtmlcmd(char** s);
extern Str checkType(Str s, Lineprop** oprop, Linecolor** ocolor);
extern int calcPosition(char* l, Lineprop* pr, int len, int pos, int bpos,
    int mode);
extern char* lastFileName(char* path);
extern char* mydirname(char* s);
extern int next_status(char c, int* status);
extern int read_token(Str buf, char** instr, int* status, int pre, int append);
extern Str correct_irrtag(int status);
extern char* conv_search_string(char* str, wc_ces f_ces);
extern int forwardSearch(Buffer* buf, char* str);
extern int backwardSearch(Buffer* buf, char* str);
extern void pcmap(void);
extern void escmap(void);
extern void escbmap(void);
extern void escdmap(char c);
extern void multimap(void);
extern Str unescape_spaces(Str s);
extern Buffer* historyBuffer(struct Hist* hist);
extern double log_like(int x);
extern struct table* newTable(void);
extern void pushdata(struct table* t, int row, int col, char* data);
extern int visible_length(char* str);
extern void align(TextLine* lbuf, int width, int mode);
extern void print_item(struct table* t, int row, int col, int width, Str buf);
extern void print_sep(struct table* t, int row, int type, int maxcol, Str buf);
extern void do_refill(struct table* tbl, int row, int col, int maxlimit);
extern void initRenderTable(void);
extern void renderTable(struct table* t, int max_width,
    struct html_feed_environ* h_env);
extern struct table* begin_table(int border, int spacing, int padding,
    int vspace);
extern void end_table(struct table* tbl);
extern void check_rowcol(struct table* tbl, struct table_mode* mode);
extern int minimum_length(char* line);
extern int feed_table(struct table* tbl, char* line, struct table_mode* mode,
    int width, int internal);
extern void feed_table1(struct table* tbl, Str tok, struct table_mode* mode,
    int width);
extern void pushTable(struct table*, struct table*);
extern struct form_list* newFormList(char* action, char* method, char* charset,
    char* enctype, char* target, char* name,
    struct form_list* _next);
extern struct form_item_list* formList_addInput(struct form_list* fl,
    struct parsed_tag* tag);
extern char* form2str(FormItemList* fi);
extern int formtype(char* typestr);
extern void formRecheckRadio(Anchor* a, Buffer* buf, FormItemList* form);
extern void formResetBuffer(Buffer* buf, AnchorList* formitem);
extern void formUpdateBuffer(Anchor* a, Buffer* buf, FormItemList* form);
extern void preFormUpdateBuffer(Buffer* buf);
extern Str textfieldrep(Str s, int width);
extern void input_textarea(FormItemList* fi);
extern void do_internal(char* action, char* data);
extern void form_write_data(FILE* f, char* boundary, char* name, char* value);
extern void form_write_from_file(FILE* f, char* boundary, char* name,
    char* filename, char* file);
extern MapList* searchMapList(Buffer* buf, char* name);
extern void follow_map(struct parsed_tagarg* arg);
#if defined(MENU_MAP) || defined(USE_IMAGE)
extern MapArea* follow_map_menu(Buffer* buf, char* name, Anchor* a_img, int x,
    int y);
#endif
extern int getMapXY(Buffer* buf, Anchor* a, int* x, int* y);
extern MapArea* retrieveCurrentMapArea(Buffer* buf);
extern Anchor* retrieveCurrentMap(Buffer* buf);
extern MapArea* newMapArea(char* url, char* target, char* alt, char* shape,
    char* coords);
extern Buffer* page_info_panel(Buffer* buf);

extern MySignalHandler reset_exit(SIGNAL_ARG);
extern MySignalHandler error_dump(SIGNAL_ARG);
extern pid_t open_pipe_rw(FILE** fr, FILE** fw);

extern void initMimeTypes(void);
extern void free_ssl_ctx(void);
extern ParsedURL* baseURL(Buffer* buf);
extern int openSocket(char* hostname, char* remoteport_name,
    unsigned short remoteport_num);

Str HTTPrequestMethod(HRequest* hr);
Str HTTPrequestURI(ParsedURL* pu, HRequest* hr);
extern URLFile openURL(char* url, ParsedURL* pu, ParsedURL* current,
    URLOption* option, FormList* request,
    TextList* extra_header, URLFile* ouf,
    HRequest* hr, unsigned char* status);
extern int mailcapMatch(struct mailcap* mcap, char* type);
extern struct mailcap* searchMailcap(struct mailcap* table, char* type);
extern void initMailcap(void);
extern char* acceptableMimeTypes(void);
extern struct mailcap* searchExtViewer(char* type);
extern Str unquote_mailcap(char* qstr, char* type, char* name, char* attr,
    int* mc_stat);
extern TextList* make_domain_list(char* domain_list);
extern int check_no_proxy(char* domain);
extern InputStream openFTPStream(ParsedURL* pu, URLFile* uf);
extern Str loadFTPDir(ParsedURL* pu, wc_ces* charset);
extern void closeFTP(void);
extern void disconnectFTP(void);
extern AnchorList* putAnchor(AnchorList* al, char* url, char* target,
    Anchor** anchor_return, char* referer,
    char* title, unsigned char key, int line,
    int pos);
extern Anchor* registerHref(Buffer* buf, char* url, char* target,
    char* referer, char* title, unsigned char key,
    int line, int pos);
extern Anchor* registerName(Buffer* buf, char* url, int line, int pos);
extern Anchor* registerImg(Buffer* buf, char* url, char* title, int line,
    int pos);
extern Anchor* registerForm(Buffer* buf, FormList* flist,
    struct parsed_tag* tag, int line, int pos);
extern int onAnchor(Anchor* a, int line, int pos);
extern Anchor* retrieveAnchor(AnchorList* al, int line, int pos);
extern Anchor* retrieveCurrentAnchor(Buffer* buf);
extern Anchor* retrieveCurrentImg(Buffer* buf);
extern Anchor* retrieveCurrentForm(Buffer* buf);
extern Anchor* searchAnchor(AnchorList* al, char* str);
extern Anchor* searchURLLabel(Buffer* buf, char* url);
extern void reAnchorWord(Buffer* buf, Line* l, int spos, int epos);
extern char* reAnchor(Buffer* buf, char* re);
extern void addMultirowsForm(Buffer* buf, AnchorList* al);
extern Anchor* closest_next_anchor(AnchorList* a, Anchor* an, int x, int y);
extern Anchor* closest_prev_anchor(AnchorList* a, Anchor* an, int x, int y);
void addMultirowsImg(Buffer* buf, AnchorList* al);
extern HmarkerList* putHmarker(HmarkerList* ml, int line, int pos, int seq);
extern void shiftAnchorPosition(AnchorList* a, HmarkerList* hl, int line,
    int pos, int shift);
extern char* getAnchorText(Buffer* buf, AnchorList* al, Anchor* a);
extern Buffer* link_list_panel(Buffer* buf);

extern Str decodeB(char** ww);
extern void decodeB_to_growbuf(struct growbuf* gb, char** ww);
extern Str decodeQ(char** ww);
extern Str decodeQP(char** ww);
extern void decodeQP_to_growbuf(struct growbuf* gb, char** ww);
extern Str decodeU(char** ww);
extern void decodeU_to_growbuf(struct growbuf* gb, char** ww);
extern Str decodeWord(char** ow, wc_ces* charset);
extern Str decodeMIME(Str orgstr, wc_ces* charset);
extern int set_param_option(char* option);
extern char* get_param_option(char* name);
extern void init_rc(void);
extern void init_tmp(void);
extern Buffer* load_option_panel(void);
extern void panel_set_option(struct parsed_tagarg*);
extern void sync_with_option(void);
extern char* rcFile(char* base);
extern char* etcFile(char* base);
extern char* confFile(char* base);
extern char* auxbinFile(char* base);
extern char* libFile(char* base);
extern char* helpFile(char* base);
extern const void* querySiteconf(const ParsedURL* query_pu, int field);
extern Str localCookie(void);
extern Str loadLocalDir(char* dirname);
extern void set_environ(char* var, char* value);
extern FILE* localcgi_post(char*, char*, FormList*, char*);
#define localcgi_get(u, q, r) localcgi_post((u), (q), NULL, (r))
extern FILE* openSecretFile(char* fname);
extern void loadPasswd(void);
extern void loadPreForm(void);
extern int find_auth_user_passwd(ParsedURL* pu, char* realm,
    Str* uname, Str* pwd, int is_proxy);
extern void add_auth_user_passwd(ParsedURL* pu, char* realm,
    Str uname, Str pwd, int is_proxy);
extern void invalidate_auth_user_passwd(ParsedURL* pu, char* realm,
    Str uname, Str pwd, int is_proxy);
extern char* last_modified(Buffer* buf);
extern Str romanNumeral(int n);
extern Str romanAlphabet(int n);
extern void setup_child(int child, int i, int f);
extern void myExec(char* command);
extern void mySystem(char* command, int background);
extern Str myExtCommand(char* cmd, char* arg, int redirect);
extern Str myEditor(char* cmd, char* file, int line);
extern int is_localhost(const char* host);
extern char* file_to_url(char* file);
extern char* url_unquote_conv(char* url, wc_ces charset);
extern char* expandName(char* name);
extern Str tmpfname(int type, char* ext);
extern time_t mymktime(char* timestr);
extern char* FQDN(char* host);
extern Str find_cookie(ParsedURL* pu);
extern int add_cookie(ParsedURL* pu, Str name, Str value, time_t expires,
    Str domain, Str path, int flag, Str comment, int version,
    Str port, Str commentURL);
extern void save_cookies(void);
extern void load_cookies(void);
extern void initCookie(void);
extern void cooLst(void);
extern Buffer* cookie_list_panel(void);
extern void set_cookie_flag(struct parsed_tagarg* arg);
extern int check_cookie_accept_domain(char* domain);
extern void docCSet(void);
extern void defCSet(void);
extern void change_charset(struct parsed_tagarg* arg);

extern void _mark(void);
extern void nextMk(void);
extern void prevMk(void);
extern void reMark(void);

#define mouse nulcmd
#define sgrmouse nulcmd
#define msToggle nulcmd
#define movMs nulcmd
#define menuMs nulcmd
#define tabMs nulcmd
#define closeTMs nulcmd

extern char* searchKeyData(void);

extern void setKeymap(char* p, int lineno, int verbose);
extern void initKeymap(int force);
extern int getFuncList(char* id);
extern int getKey(char* s);
extern char* getKeyData(int key);
extern char* getWord(char** str);
extern char* getQWord(char** str);
struct regex;
extern char* getRegexWord(const char** str, struct regex** regex_ret);

extern void new_menu(Menu* menu, MenuItem* item);
extern void geom_menu(Menu* menu, int x, int y, int mselect);
extern void draw_all_menu(Menu* menu);
extern void draw_menu(Menu* menu);
extern void draw_menu_item(Menu* menu, int mselect);
extern int select_menu(Menu* menu, int mselect);
extern void goto_menu(Menu* menu, int mselect, int down);
extern void up_menu(Menu* menu, int n);
extern void down_menu(Menu* menu, int n);
extern int action_menu(Menu* menu);
extern void popup_menu(Menu* parent, Menu* menu);
extern void guess_menu_xy(Menu* menu, int width, int* x, int* y);
extern void new_option_menu(Menu* menu, char** label, int* variable,
    void (*func)());

extern int setMenuItem(MenuItem* item, char* type, char* line);
extern int addMenuList(MenuList** list, char* id);
extern int getMenuN(MenuList* list, char* id);

extern void popupMenu(int x, int y, Menu* menu);
extern void mainMenu(int x, int y);
extern void mainMn(void);
extern void selMn(void);
extern void tabMn(void);
extern void optionMenu(int x, int y, char** label, int* variable, int initial,
    void (*func)());
extern void initMenu(void);

extern void dictword(void);
extern void dictwordat(void);
extern char* guess_save_name(Buffer* buf, char* file);

extern void wrapToggle(void);
extern void saveBufferInfo(void);

extern Str getLinkNumberStr(int correction);

extern void dispVer(void);
