/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Wed Feb 10 12:47:03 1999
 */

// extern void FUNC_NAME(void) from DEFUN
#include "defun.h"

extern void addDownloadList(pid_t pid, char* url, char* save, char* lock, long long size);
extern void stopDownload(void);
extern int checkDownloadList(void);
extern void download_action(struct parsed_tagarg* arg);
extern Buffer* newBuffer();
extern Buffer* nullBuffer(void);
extern void clearBuffer(Buffer* buf);
extern void discardBuffer(Buffer* buf);
extern Buffer* namedBuffer(Buffer* first, char* name);
extern Buffer* deleteBuffer(Buffer* first, Buffer* delbuf);
extern Buffer* replaceBuffer(Buffer* first, Buffer* delbuf, Buffer* newbuf);
extern Buffer* nthBuffer(Buffer* firstbuf, int n);
extern void gotoRealLine(Buffer* buf, int n);
extern void gotoLine(Buffer* buf, int n);
extern Buffer* selectBuffer(Buffer* firstbuf, Buffer* currentbuf,
    char* selectchar);
extern void reshapeBuffer(Buffer* buf);
extern void copyBuffer(Buffer* a, Buffer* b);
extern Buffer* prevBuffer(Buffer* first, Buffer* buf);
extern int writeBufferCache(Buffer* buf);
extern int readBufferCache(Buffer* buf);
extern void addChar(char c, Lineprop mode);
extern void addMChar(char* c, Lineprop mode, size_t len);
extern Buffer* message_list_panel(void);

#define disp_message_nomouse disp_message
extern void set_delayed_message(char* s);
extern void cursorUp0(Buffer* buf, int n);
extern void cursorUp(Buffer* buf, int n);
extern void cursorDown0(Buffer* buf, int n);
extern void cursorDown(Buffer* buf, int n);
extern void cursorUpDown(Buffer* buf, int n);
extern void cursorRight(Buffer* buf, int n);
extern void cursorLeft(Buffer* buf, int n);
extern void cursorHome(Buffer* buf);
extern void arrangeCursor(Buffer* buf);
extern void arrangeLine(Buffer* buf);
extern void cursorXY(Buffer* buf, int x, int y);
extern void restorePosition(Buffer* buf, Buffer* orig);
extern int columnSkip(Buffer* buf, int offset);
extern Line* lineSkip(Buffer* buf, Line* line, int offset, int last);
extern Line* currentLineSkip(Buffer* buf, Line* line, int offset, int last);
extern int gethtmlcmd(char** s);
extern Str checkType(Str s, Lineprop** oprop, Linecolor** ocolor);
extern char* lastFileName(char* path);
extern char* mydirname(char* s);
extern int next_status(char c, int* status);
extern int read_token(Str buf, char** instr, int* status, int pre, int append);
extern Str correct_irrtag(int status);
extern char* conv_search_string(char* str, wc_ces f_ces);
extern int forwardSearch(Buffer* buf, char* str);
extern int backwardSearch(Buffer* buf, char* str);
extern void escdmap(char c);
extern Buffer* historyBuffer(struct Hist* hist);
extern double log_like(int x);
extern struct table* newTable(void);
extern void pushdata(struct table* t, int row, int col, char* data);
extern int visible_length(char* str);
extern void align(TextLine* lbuf, int width, int mode);
extern void print_item(struct table* t, int row, int col, int width, Str buf);
extern void print_sep(struct table* t, int row, int type, int maxcol, Str buf);
extern void do_refill(struct table* tbl, int row, int col, int maxlimit);
extern void initRenderTable(void);
extern void renderTable(struct table* t, int max_width,
    struct html_feed_environ* h_env);
extern struct table* begin_table(int border, int spacing, int padding,
    int vspace);
extern void end_table(struct table* tbl);
extern void check_rowcol(struct table* tbl, struct table_mode* mode);
extern int minimum_length(char* line);
extern int feed_table(struct table* tbl, char* line, struct table_mode* mode,
    int width, int internal);
extern void feed_table1(struct table* tbl, Str tok, struct table_mode* mode,
    int width);
extern void pushTable(struct table*, struct table*);
extern struct form_list* newFormList(char* action, char* method, char* charset,
    char* enctype, char* target, char* name,
    struct form_list* _next);
extern struct form_item_list* formList_addInput(struct form_list* fl,
    struct parsed_tag* tag);
extern char* form2str(FormItemList* fi);
extern int formtype(char* typestr);
extern void formRecheckRadio(Anchor* a, Buffer* buf, FormItemList* form);
extern void formResetBuffer(Buffer* buf, AnchorList* formitem);
extern void formUpdateBuffer(Anchor* a, Buffer* buf, FormItemList* form);
extern void preFormUpdateBuffer(Buffer* buf);
extern Str textfieldrep(Str s, int width);
extern void input_textarea(FormItemList* fi);
extern void do_internal(char* action, char* data);
extern void form_write_data(FILE* f, char* boundary, char* name, char* value);
extern void form_write_from_file(FILE* f, char* boundary, char* name,
    char* filename, char* file);
extern MapList* searchMapList(Buffer* buf, char* name);
extern void follow_map(struct parsed_tagarg* arg);
#if defined(MENU_MAP) || defined(USE_IMAGE)
extern MapArea* follow_map_menu(Buffer* buf, char* name, Anchor* a_img, int x,
    int y);
#endif
extern int getMapXY(Buffer* buf, Anchor* a, int* x, int* y);
extern MapArea* retrieveCurrentMapArea(Buffer* buf);
extern Anchor* retrieveCurrentMap(Buffer* buf);
extern MapArea* newMapArea(char* url, char* target, char* alt, char* shape,
    char* coords);
extern Buffer* page_info_panel(Buffer* buf);

extern MySignalHandler reset_exit(SIGNAL_ARG);
extern MySignalHandler error_dump(SIGNAL_ARG);
extern pid_t open_pipe_rw(FILE** fr, FILE** fw);

extern void initMimeTypes(void);
extern void free_ssl_ctx(void);
extern ParsedURL* baseURL(Buffer* buf);
extern int openSocket(char* hostname, char* remoteport_name,
    unsigned short remoteport_num);

Str HTTPrequestMethod(HRequest* hr);
Str HTTPrequestURI(ParsedURL* pu, HRequest* hr);
extern URLFile openURL(char* url, ParsedURL* pu, ParsedURL* current,
    URLOption* option, FormList* request,
    TextList* extra_header, URLFile* ouf,
    HRequest* hr, unsigned char* status);
extern int mailcapMatch(struct mailcap* mcap, char* type);
extern struct mailcap* searchMailcap(struct mailcap* table, char* type);
extern void initMailcap(void);
extern char* acceptableMimeTypes(void);
extern struct mailcap* searchExtViewer(char* type);
extern Str unquote_mailcap(char* qstr, char* type, char* name, char* attr,
    int* mc_stat);
extern TextList* make_domain_list(char* domain_list);
extern int check_no_proxy(char* domain);
extern AnchorList* putAnchor(AnchorList* al, char* url, char* target,
    Anchor** anchor_return, char* referer,
    char* title, unsigned char key, int line,
    int pos);
extern Anchor* registerHref(Buffer* buf, char* url, char* target,
    char* referer, char* title, unsigned char key,
    int line, int pos);
extern Anchor* registerName(Buffer* buf, char* url, int line, int pos);
extern Anchor* registerImg(Buffer* buf, char* url, char* title, int line,
    int pos);
extern Anchor* registerForm(Buffer* buf, FormList* flist,
    struct parsed_tag* tag, int line, int pos);
extern int onAnchor(Anchor* a, int line, int pos);
extern Anchor* retrieveAnchor(AnchorList* al, int line, int pos);
extern Anchor* retrieveCurrentAnchor(Buffer* buf);
extern Anchor* retrieveCurrentImg(Buffer* buf);
extern Anchor* retrieveCurrentForm(Buffer* buf);
extern Anchor* searchAnchor(AnchorList* al, char* str);
extern Anchor* searchURLLabel(Buffer* buf, char* url);
extern void reAnchorWord(Buffer* buf, Line* l, int spos, int epos);
extern char* reAnchor(Buffer* buf, char* re);
extern void addMultirowsForm(Buffer* buf, AnchorList* al);
extern Anchor* closest_next_anchor(AnchorList* a, Anchor* an, int x, int y);
extern Anchor* closest_prev_anchor(AnchorList* a, Anchor* an, int x, int y);
void addMultirowsImg(Buffer* buf, AnchorList* al);
extern HmarkerList* putHmarker(HmarkerList* ml, int line, int pos, int seq);
extern void shiftAnchorPosition(AnchorList* a, HmarkerList* hl, int line,
    int pos, int shift);
extern char* getAnchorText(Buffer* buf, AnchorList* al, Anchor* a);
extern Buffer* link_list_panel(Buffer* buf);

extern Str decodeB(char** ww);
extern void decodeB_to_growbuf(struct growbuf* gb, char** ww);
extern Str decodeQ(char** ww);
extern Str decodeQP(char** ww);
extern void decodeQP_to_growbuf(struct growbuf* gb, char** ww);
extern Str decodeU(char** ww);
extern void decodeU_to_growbuf(struct growbuf* gb, char** ww);
extern Str decodeWord(char** ow, wc_ces* charset);
extern Str decodeMIME(Str orgstr, wc_ces* charset);
extern int set_param_option(char* option);
extern char* get_param_option(char* name);
extern void init_rc(void);
extern void init_tmp(void);
extern Buffer* load_option_panel(void);
extern void panel_set_option(struct parsed_tagarg*);
extern void sync_with_option(void);
extern char* rcFile(char* base);
extern char* etcFile(char* base);
extern char* confFile(char* base);
extern char* auxbinFile(char* base);
extern char* libFile(char* base);
extern char* helpFile(char* base);
extern const void* querySiteconf(const ParsedURL* query_pu, int field);
extern Str localCookie(void);
extern Str loadLocalDir(char* dirname);
extern void set_environ(char* var, char* value);
extern FILE* localcgi_post(char*, char*, FormList*, char*);
#define localcgi_get(u, q, r) localcgi_post((u), (q), NULL, (r))
extern FILE* openSecretFile(char* fname);
extern void loadPasswd(void);
extern void loadPreForm(void);
extern int find_auth_user_passwd(ParsedURL* pu, char* realm,
    Str* uname, Str* pwd, int is_proxy);
extern void add_auth_user_passwd(ParsedURL* pu, char* realm,
    Str uname, Str pwd, int is_proxy);
extern void invalidate_auth_user_passwd(ParsedURL* pu, char* realm,
    Str uname, Str pwd, int is_proxy);
extern char* last_modified(Buffer* buf);
extern Str romanNumeral(int n);
extern Str romanAlphabet(int n);
extern void setup_child(int child, int i, int f);
extern void myExec(char* command);
extern void mySystem(char* command, int background);
extern Str myExtCommand(char* cmd, char* arg, int redirect);
extern Str myEditor(char* cmd, char* file, int line);
extern int is_localhost(const char* host);
extern char* file_to_url(char* file);
extern char* url_unquote_conv(char* url, wc_ces charset);
extern char* expandName(char* name);
extern Str tmpfname(int type, char* ext);
extern time_t mymktime(char* timestr);
extern char* FQDN(char* host);
extern Str find_cookie(ParsedURL* pu);
extern int add_cookie(ParsedURL* pu, Str name, Str value, time_t expires,
    Str domain, Str path, int flag, Str comment, int version,
    Str port, Str commentURL);
extern void save_cookies(void);
extern void load_cookies(void);
extern void initCookie(void);
extern Buffer* cookie_list_panel(void);
extern void set_cookie_flag(struct parsed_tagarg* arg);
extern int check_cookie_accept_domain(char* domain);
extern void change_charset(struct parsed_tagarg* arg);

extern void new_menu(Menu* menu, MenuItem* item);
extern void geom_menu(Menu* menu, int x, int y, int mselect);
extern void draw_all_menu(Menu* menu);
extern void draw_menu(Menu* menu);
extern void draw_menu_item(Menu* menu, int mselect);
extern int select_menu(Menu* menu, int mselect);
extern void goto_menu(Menu* menu, int mselect, int down);
extern void up_menu(Menu* menu, int n);
extern void down_menu(Menu* menu, int n);
extern int action_menu(Menu* menu);
extern void popup_menu(Menu* parent, Menu* menu);
extern void guess_menu_xy(Menu* menu, int width, int* x, int* y);
extern void new_option_menu(Menu* menu, char** label, int* variable,
    void (*func)());

extern int setMenuItem(MenuItem* item, char* type, char* line);
extern int addMenuList(MenuList** list, char* id);
extern int getMenuN(MenuList* list, char* id);

extern void popupMenu(int x, int y, Menu* menu);
extern void mainMenu(int x, int y);
extern void optionMenu(int x, int y, char** label, int* variable, int initial,
    void (*func)());
extern void initMenu(void);

extern char* guess_save_name(Buffer* buf, char* file);

extern void saveBufferInfo(void);

extern Str getLinkNumberStr(int correction);
