pub const SRCS = [_][]const u8{
    "src/keybind.c",
    "src/datetime.c",
    "src/trap_jmp.c",
    "src/utf8.c",
    "src/siteconf.c",
    "src/text.c",
    "src/tmpfile.c",
    "src/alloc.c",
    "src/core.c",
    "src/shell.c",
    "src/main.c",
    "src/defun.c",
    "src/file.c",
    "src/linein.c",
    "src/rc.c",
    "src/menu.c",
    "src/symbol.c",
    "src/entity.c",
    "src/entity_table.c",
    "src/mimehead.c",
    "src/regex.c",
    "src/func.c",
    "src/history.c",
    "src/Str.c",
    "src/textlist.c",
    "src/myctype.c",
    "src/hash.c",
    "src/version.c",
    "src/rand48.c",
    "src/romannum.c",
    "src/os.c",
    "src/libnkf.c",

    "src/buffer/downloadlist.c",
    "src/buffer/image.c",
    "src/buffer/document.c",
    "src/buffer/buffer.c",
    "src/buffer/display.c",
    "src/buffer/tabbuffer.c",
    "src/buffer/line.c",
    "src/buffer/search.c",

    "src/term/scr.c",
    "src/term/terms.c",
    "src/term/termcon_termcap.c",

    "src/input/localcgi.c",
    "src/input/loader.c",
    "src/input/isocket.c",
    "src/input/compression.c",
    "src/input/growbuf.c",
    "src/input/istream.c",
    "src/input/url_stream.c",
    "src/input/ftp.c",
    "src/input/http_cookie.c",
    "src/input/http_response.c",
    "src/input/http_auth.c",
    "src/input/http_auth_digest.c",
    "src/input/url.c",

    "src/html/html_renderer.c",
    "src/html/html_textarea.c",
    "src/html/html_text.c",
    "src/html/table.c",
    "src/html/form.c",
    "src/html/map.c",
    "src/html/anchor.c",
    "src/html/parsetagx.c",
    "src/html/tagtable.c",
    "src/html/parsetag.c",
    "src/html/html_readbuffer.c",
    "src/html/html_parser.c",
};

pub const SRCS_POSIX = [_][]const u8{
    "src/term/tty_posix.c",
    "src/term/termsize_posix.c",
    "src/input/localcgi_posix.c",
    "src/os_posix.c",
    "src/etc_posix.c",
    "src/input/isocket_posix.c",
};

pub const SRCS_WIN32 = [_][]const u8{
    "src/term/tty_win32.c",
    "src/term/termsize_win32.c",
    "src/input/localcgi_win32.c",
    "src/os_win32.c",
    "src/etc_win32.c",
    "src/input/isocket_win32.c",
};
