pub const SRCS = [_][]const u8{
    "src/main.c",
    "src/mainloop.c",
    "src/keybind.c",
    "src/dict.c",
    "src/trap_jmp.c",
    "src/siteconf.c",
    "src/alloc.c",
    "src/core.c",
    "src/defun.c",
    "src/linein.c",
    "src/rc.c",
    "src/func.c",
    "src/history.c",
    "src/hash.c",
    "src/version.c",
    "src/rand48.c",
    "src/os.c",

    "src/file/file.c",
    "src/file/shell.c",
    "src/file/tmpfile.c",

    "src/text/libnkf.c",
    "src/text/text.c",
    "src/text/symbol.c",
    "src/text/entity.c",
    "src/text/entity_table.c",
    "src/text/romannum.c",
    "src/text/myctype.c",
    "src/text/Str.c",
    "src/text/regex.c",
    "src/text/utf8.c",
    "src/text/datetime.c",
    "src/text/textlist.c",

    "src/buffer/downloadlist.c",
    "src/buffer/image.c",
    "src/buffer/document.c",
    "src/buffer/viewport.c",
    "src/buffer/buffer.c",
    "src/buffer/display.c",
    "src/buffer/tabbuffer.c",
    "src/buffer/line.c",
    "src/buffer/search.c",
    "src/buffer/message.c",

    "src/term/scr.c",
    "src/term/terms.c",
    "src/term/termcon_termcap.c",

    "src/input/content.c",
    "src/input/ext_mime.c",
    "src/input/mimehead.c",
    "src/input/localcgi.c",
    "src/input/loader.c",
    "src/input/isocket.c",
    // "src/input/compression.c",
    "src/input/growbuf.c",
    "src/input/istream.c",
    "src/input/ftp.c",
    "src/input/http_cookie.c",
    "src/input/http.c",
    "src/input/https.c",
    "src/input/http_auth.c",
    "src/input/http_auth_digest.c",
    "src/input/http_stream.c",
    "src/input/url.c",
    "src/input/stream_buffer.c",
    "src/input/proxy.c",

    "src/html/html_renderer.c",
    "src/html/html_textarea.c",
    "src/html/html_text.c",
    "src/html/table.c",
    "src/html/form.c",
    "src/html/map.c",
    "src/html/anchor.c",
    "src/html/html_tagtable.c",
    "src/html/html_tag.c",
    "src/html/html_readbuffer.c",
    "src/html/html_parser.c",
    "src/html/html_types.c",
};

pub const SRCS_POSIX = [_][]const u8{
    "src/term/tty_posix.c",
    "src/term/termsize_posix.c",
    "src/input/localcgi_posix.c",
    "src/os_posix.c",
    "src/input/isocket_posix.c",
};

pub const SRCS_WIN32 = [_][]const u8{
    "src/term/tty_win32.c",
    "src/term/termsize_win32.c",
    "src/input/localcgi_win32.c",
    "src/os_win32.c",
    "src/input/isocket_win32.c",
};
