/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Wed Feb 10 12:47:03 1999
 */
#include "func.h"

extern void nulcmd(struct Current current);
extern void pgFore(struct Current current);
extern void pgBack(struct Current current);
extern void hpgFore(struct Current current);
extern void hpgBack(struct Current current);
extern void lup1(struct Current current);
extern void ldown1(struct Current current);
extern void ctrCsrV(struct Current current);
extern void ctrCsrH(struct Current current);
extern void rdrwSc(struct Current current);
extern void srchfor(struct Current current);
extern void isrchfor(struct Current current);
extern void srchbak(struct Current current);
extern void isrchbak(struct Current current);
extern void srchnxt(struct Current current);
extern void srchprv(struct Current current);
extern void shiftl(struct Current current);
extern void shiftr(struct Current current);
extern void col1R(struct Current current);
extern void col1L(struct Current current);
extern void setEnv(struct Current current);
extern void readsh(struct Current current);
extern void execsh(struct Current current);
extern void ldfile(struct Current current);
extern void ldhelp(struct Current current);
extern void movL(struct Current current);
extern void movL1(struct Current current);
extern void movD(struct Current current);
extern void movD1(struct Current current);
extern void movU(struct Current current);
extern void movU1(struct Current current);
extern void movR(struct Current current);
extern void movR1(struct Current current);
extern void movLW(struct Current current);
extern void movRW(struct Current current);
extern void qquitfm(struct Current current);
extern void quitfm(struct Current current);
extern void selBuf(struct Current current);
extern void susp(struct Current current);
extern void goLine(struct Current current);
extern void goLineF(struct Current current);
extern void goLineL(struct Current current);
extern void linbeg(struct Current current);
extern void linend(struct Current current);
extern void editBf(struct Current current);
extern void editScr(struct Current current);
extern void followA(struct Current current);
extern void bufferA(struct Current current);
extern void followI(struct Current current);
extern void submitForm(struct Current current);
extern void followForm(struct Current current);
extern void topA(struct Current current);
extern void lastA(struct Current current);
extern void nthA(struct Current current);
extern void onA(struct Current current);

extern void nextA(struct Current current);
extern void prevA(struct Current current);
extern void nextVA(struct Current current);
extern void prevVA(struct Current current);
extern void nextL(struct Current current);
extern void nextLU(struct Current current);
extern void nextR(struct Current current);
extern void nextRD(struct Current current);
extern void nextD(struct Current current);
extern void nextU(struct Current current);
extern void nextBf(struct Current current);
extern void prevBf(struct Current current);
extern void backBf(struct Current current);
extern void deletePrevBuf(struct Current current);
extern void goURL(struct Current current);
extern void goHome(struct Current current);
extern void gorURL(struct Current current);
extern void ldBmark(struct Current current);
extern void adBmark(struct Current current);
extern void ldOpt(struct Current current);
extern void setOpt(struct Current current);
extern void pginfo(struct Current current);
extern void msgs(struct Current current);
extern void svA(struct Current current);
extern void svI(struct Current current);
extern void svBuf(struct Current current);
extern void svSrc(struct Current current);
extern void peekURL(struct Current current);
extern void peekIMG(struct Current current);
extern void curURL(struct Current current);
extern void vwSrc(struct Current current);
extern void reload(struct Current current);
extern void reshape(struct Current current);
extern void chkURL(struct Current current);
extern void chkWORD(struct Current current);
#define chkNMID nulcmd
#define rFrame nulcmd;
extern void extbrz(struct Current current);
extern void linkbrz(struct Current current);
extern void curlno(struct Current current);
extern void execCmd(struct Current current);
#define dispI nulcmd
#define stopI nulcmd
extern void reinit(struct Current current);
extern void defKey(struct Current current);
extern void newT(struct Current current);
extern void closeT(struct Current current);
extern void nextT(struct Current current);
extern void prevT(struct Current current);
extern void tabA(struct Current current);
extern void tabURL(struct Current current);
extern void tabrURL(struct Current current);
extern void tabR(struct Current current);
extern void tabL(struct Current current);
extern void ldDL(struct Current current);
extern void linkLst(struct Current current);
#define linkMn nulcmd
#define accessKey nulcmd
#define listMn nulcmd
#define movlistMn nulcmd
extern void undoPos(struct Current current);
extern void redoPos(struct Current current);
extern void cursorTop(struct Current current);
extern void cursorMiddle(struct Current current);
extern void cursorBottom(struct Current current);

#define docCSet nulcmd
#define defCSet nulcmd

#define _mark nulcmd
#define nextMk nulcmd
#define prevMk nulcmd
#define reMark nulcmd

#define mouse nulcmd
#define sgrmouse nulcmd
#define msToggle nulcmd
#define movMs nulcmd
#define menuMs nulcmd
#define tabMs nulcmd
#define closeTMs nulcmd

#define mainMn nulcmd
#define selMn selBuf
#define tabMn nulcmd

extern void dictword(struct Current current);
extern void dictwordat(struct Current current);
extern void wrapToggle(struct Current current);
extern void dispVer(struct Current current);
void cooLst(struct Current current);
extern void ldHist(struct Current current);
